#!/usr/bin/env python3
"""
assert_invariants.py — Runtime invariant guards for /hydra-autopilot decide.py
(issue #426, INV-001 through INV-008).

Each invariant has a unique greppable ID (`INV-001`, `INV-002`, ...) so
crash logs are easy to triage. Violations raise `InvariantError` with the
ID + a short reason; the playbook surfaces the crash and exits the
current decision turn (the next turn starts fresh).

The guards are intentionally CHEAP — every guard is O(n) over the actions
in a single plan plus O(1) state lookups. They run on every plan
generated by decide.py before the model executes any action.

Greppable IDs (also asserted by `test/autopilot-invariants.test.mts`):

  INV-001  never auto-merge a Tier-0 non-mechanical PR
  INV-002  never dispatch into a busy pipeline slot
  INV-003  never re-dispatch a class in burned_classes (soft cap, #395)
  INV-004  never re-reap a task_id already in reaped_task_ids (#411)
  INV-005  emit `terminate` when cumulative_tokens >= budget
  INV-006  reap actions precede dispatch actions in the same plan
  INV-007  auto-merge only when the QA verdict is PASS
  INV-008  no dispatch for a scope-disallowed class (except `health`)

Usage from decide.py / Bash:

  python3 -c "
  from scripts.autopilot.assert_invariants import check_plan
  check_plan(plan_dict, state_dict)
  "

Or as a CLI for diagnostic use:

  echo "$PLAN_JSON" | python3 scripts/autopilot/assert_invariants.py - state.json
"""

from __future__ import annotations

import json
import sys
from typing import Iterable


class InvariantError(AssertionError):
    """Raised when an autopilot decision plan violates a runtime invariant.

    The `code` attribute is the INV-NNN identifier; the message follows
    `INV-NNN: <reason>` so a single grep across logs surfaces every hit.
    """

    def __init__(self, code: str, reason: str) -> None:
        super().__init__(f"{code}: {reason}")
        self.code = code
        self.reason = reason


# Scope filter mirror — kept in sync with decide.py. We DO NOT import
# decide here to keep `assert_invariants.py` standalone (tests can run
# without pulling in the larger module).
SCOPE_ORCH_ONLY_EXCLUDE = ("dev_target", "research_target", "qa_target", "sweep_target", "discover_target")
SCOPE_TARGET_ONLY_EXCLUDE = ("dev_orch", "research_orch", "qa_orch", "sweep_orch", "discover_orch")


def _scope_excluded(scope: str, cls: str) -> bool:
    if scope == "all":
        return False
    # Only `health` is scope-agnostic — see decide.py:scope_excluded() for
    # the rationale.
    if cls == "health":
        return False
    if scope == "orch-only":
        return cls in SCOPE_ORCH_ONLY_EXCLUDE
    if scope == "target-only":
        return cls in SCOPE_TARGET_ONLY_EXCLUDE
    return False


# ---------------------------------------------------------------------------
# Individual invariant checks
# ---------------------------------------------------------------------------

def check_inv001(actions: list[dict]) -> None:
    """INV-001 never auto-merge a Tier-0 non-mechanical PR."""
    for a in actions:
        if a.get("type") != "auto-merge":
            continue
        try:
            tier = int(a.get("tier", -1))
        except (TypeError, ValueError):
            tier = -1
        if tier == 0:
            raise InvariantError("INV-001", f"auto-merge on Tier-0 PR #{a.get('pr_number')}")


def check_inv002(actions: list[dict], state: dict) -> None:
    """INV-002 never dispatch into a busy pipeline slot.

    Defensive against a malformed `slots` field (issue #431): an empty
    dict or a partially-initialized dict (missing one or more of the 6
    named pipeline keys) is treated as "all unlisted slots free". The
    within-plan tracking (`occupied.add(slot)` below) still catches
    double-dispatches in the same plan even when the slot key never
    existed in the state file. bootstrap.sh is the authoritative source
    of all 6 keys; this method tolerates pre-bootstrap state shapes so
    a single-run regression can't wedge the loop.
    """
    slots = state.get("slots") or {}
    # Track within-plan dispatches as occupying the slot, so a single plan
    # can't double-fill the same slot.
    occupied = {k for k, v in slots.items() if v is not None}
    for a in actions:
        if a.get("type") != "dispatch":
            continue
        slot = a.get("slot")
        if slot in occupied:
            raise InvariantError("INV-002", f"dispatch into busy slot {slot!r}")
        occupied.add(slot)


def check_inv003(actions: list[dict], state: dict) -> None:
    """INV-003 never re-dispatch a class in burned_classes (soft cap, #395)."""
    burned = set(state.get("burned_classes") or [])
    for a in actions:
        if a.get("type") != "dispatch":
            continue
        slot = a.get("slot")
        if slot in burned:
            raise InvariantError("INV-003", f"dispatch into burned class {slot!r}")


def check_inv004(actions: list[dict], state: dict) -> None:
    """INV-004 never re-reap a task_id already in reaped_task_ids (#411)."""
    reaped = set(state.get("reaped_task_ids") or [])
    seen_in_plan: set[str] = set()
    for a in actions:
        if a.get("type") != "reap":
            continue
        task_id = a.get("task_id")
        if task_id and (task_id in reaped or task_id in seen_in_plan):
            raise InvariantError("INV-004", f"re-reap of task_id={task_id!r}")
        if task_id:
            seen_in_plan.add(task_id)


def check_inv005(actions: list[dict], state: dict) -> None:
    """INV-005 emit `terminate` when cumulative_tokens >= budget."""
    limits = state.get("limits") or {}
    budget = int(limits.get("token_budget", 2_000_000))
    cumulative = int(state.get("cumulative_tokens", 0))
    if cumulative >= budget:
        if not any(a.get("type") == "terminate" for a in actions):
            raise InvariantError(
                "INV-005",
                f"budget exhausted (cumulative={cumulative}/{budget}) but plan has no terminate action",
            )


def check_inv006(actions: list[dict]) -> None:
    """INV-006 reap actions precede dispatch actions in the same plan."""
    seen_dispatch = False
    for a in actions:
        t = a.get("type")
        if t == "dispatch":
            seen_dispatch = True
        elif t == "reap" and seen_dispatch:
            raise InvariantError("INV-006", "reap after dispatch in same plan")


def check_inv007(actions: list[dict]) -> None:
    """INV-007 auto-merge only when the QA verdict is PASS.

    A plan-level guard: every auto-merge action must carry a `qa_verdict:
    "PASS"` payload (set by decide.py from the qa-verdict event). Plans
    constructed directly in tests can pass `verdict: "PASS"` to opt in.
    """
    for a in actions:
        if a.get("type") != "auto-merge":
            continue
        verdict = a.get("qa_verdict") or a.get("verdict")
        if verdict and verdict != "PASS":
            raise InvariantError(
                "INV-007",
                f"auto-merge with qa_verdict={verdict!r} (must be PASS)",
            )


def check_inv008(actions: list[dict], state: dict) -> None:
    """INV-008 no dispatch for a scope-disallowed class (except `health`)."""
    limits = state.get("limits") or {}
    scope = str(limits.get("scope", "all"))
    for a in actions:
        if a.get("type") != "dispatch":
            continue
        slot = str(a.get("slot") or "")
        if slot == "health":
            continue
        if _scope_excluded(scope, slot):
            raise InvariantError("INV-008", f"dispatch {slot!r} disallowed under scope={scope!r}")


# ---------------------------------------------------------------------------
# Aggregate entry point
# ---------------------------------------------------------------------------

ALL_CHECKS = (
    ("INV-001", check_inv001, False),
    ("INV-002", check_inv002, True),
    ("INV-003", check_inv003, True),
    ("INV-004", check_inv004, True),
    ("INV-005", check_inv005, True),
    ("INV-006", check_inv006, False),
    ("INV-007", check_inv007, False),
    ("INV-008", check_inv008, True),
)


def check_plan(plan: dict | object, state: dict) -> None:
    """Validate a decide.py Plan (either a dict or an object with .actions).

    Raises `InvariantError` on the first violated invariant. Caller is
    responsible for logging + recovering.
    """
    actions = _extract_actions(plan)
    for code, fn, needs_state in ALL_CHECKS:
        try:
            if needs_state:
                fn(actions, state)  # type: ignore[arg-type]
            else:
                fn(actions)  # type: ignore[call-arg]
        except InvariantError:
            raise
        except Exception as exc:  # pragma: no cover — guards must never throw unexpectedly
            raise InvariantError(code, f"check raised {exc.__class__.__name__}: {exc}") from exc


def _extract_actions(plan: dict | object) -> list[dict]:
    if isinstance(plan, dict):
        actions = plan.get("actions")
    else:
        actions = getattr(plan, "actions", None)
    if not isinstance(actions, list):
        raise InvariantError("INV-000", "plan has no `actions` list")
    return actions


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(
            "usage: assert_invariants.py <plan.json|-> <state.json>\n"
            "  plan can be a path or `-` to read JSON from stdin",
            file=sys.stderr,
        )
        return 2
    plan_arg = argv[1]
    if plan_arg == "-":
        plan = json.loads(sys.stdin.read())
    else:
        with open(plan_arg, "r", encoding="utf-8") as fh:
            plan = json.load(fh)
    with open(argv[2], "r", encoding="utf-8") as fh:
        state = json.load(fh)
    try:
        check_plan(plan, state)
    except InvariantError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
