/**
 * Regression test for issue #3850 — rate-vs-baseline escalation gate for the
 * steady-rate cues (acceptance-criterion-unmet / -deferred).
 *
 * The count-based gate (`shouldEscalateAtHitCount`) re-bumps a steady-rate
 * cue's OPEN issue every +10 hits forever. Issue #3850 adds a DOWNSTREAM rate
 * gate inside escalation.ts's OPEN-issue comment-bump branch: for the two
 * rate-gated cues, a comment-bump POSTs only when the cue's recent hit rate
 * has risen above its own creation-anchored baseline. Creation + reopen paths
 * are never gated; non-rate-gated cues are byte-identical.
 *
 * Two test groups:
 *   1. Pure policy (cue-policy.ts) — deterministic, no gh, no Redis. Includes
 *      a replay of the REAL #2528 escalation history that grounds the
 *      window/multiplier constants.
 *   2. Integration (escalation.ts) — fake gh script; asserts the gate's
 *      skipped/commented/fail-open behaviour through escalatePatternToIssue.
 */

import { test, describe, before, beforeEach, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile, rm, chmod } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { existsSync } from "node:fs";

// Pure cue-policy helpers — zero-IO leaf, safe to import at module load.
import {
  isRateGatedCue,
  parseEscalationBumpSeries,
  shouldRateEscalate,
  RATE_ESCALATION_WINDOW_DAYS,
  RATE_ESCALATION_MULTIPLIER,
} from "../src/pattern-memory/cue-policy.ts";

const DAY_MS = 86_400_000;
/** ISO timestamp `offsetDays` from the real wall-clock now (test-only). */
const isoFromNow = (offsetDays: number): string =>
  new Date(Date.now() + offsetDays * DAY_MS).toISOString();

// ===========================================================================
// 1. Pure policy
// ===========================================================================

describe("rate-gate pure policy (cue-policy.ts, issue #3850)", () => {
  // -------------------------------------------------------------------------
  // isRateGatedCue
  // -------------------------------------------------------------------------

  test("isRateGatedCue: only the two steady-rate cues are gated", () => {
    assert.equal(isRateGatedCue("acceptance-criterion-unmet"), true);
    assert.equal(isRateGatedCue("acceptance-criterion-deferred"), true);
    // The never-escalate sentinel cue is NOT rate-gated (it never reaches the
    // gate — its escalate intent is always false upstream).
    assert.equal(isRateGatedCue("no-agent-spawn-tool-run-inline"), false);
    // Ordinary low-rate cues keep the default path.
    assert.equal(isRateGatedCue("scope-creep"), false);
    assert.equal(isRateGatedCue("verification-failure"), false);
    assert.equal(isRateGatedCue(""), false);
  });

  test("constants match the empirically-fitted values cited in the comment", () => {
    assert.equal(RATE_ESCALATION_WINDOW_DAYS, 7);
    assert.equal(RATE_ESCALATION_MULTIPLIER, 1.5);
  });

  // -------------------------------------------------------------------------
  // parseEscalationBumpSeries — validated against the REAL #2528 body/comment
  // shapes (escalation.ts's own buildBody / buildCommentBody output format).
  // -------------------------------------------------------------------------

  test("parseEscalationBumpSeries: reconstructs creation + bumps from the real #2528 format", () => {
    const body =
      "Auto-escalated by the learning system after 83 hits on cue `acceptance-criterion-unmet`.\n\n" +
      "**Kind:** lesson\n**Hit count:** 83";
    const comments = [
      // Non-escalation noise that must be IGNORED.
      { body: "> *This was generated by AI during triage.*\n\nAuto-triaged.", createdAt: "2026-06-28T12:01:00Z" },
      { body: "> *Automated sweep*\n\nReconciled from needs-info.", createdAt: "2026-07-30T15:07:42Z" },
      // Real escalation bumps.
      { body: "Pattern still firing — now 150 hits on `acceptance-criterion-unmet`.\nLast reference: x", createdAt: "2026-07-24T23:16:03Z" },
      { body: "Pattern still firing — now 160 hits on `acceptance-criterion-unmet`.", createdAt: "2026-07-30T04:45:17Z" },
      { body: "Pattern still firing — now 200 hits on `acceptance-criterion-unmet`.", createdAt: "2026-08-08T11:41:32Z" },
    ];
    const series = parseEscalationBumpSeries(body, "2026-06-28T11:33:19Z", comments);
    // Creation point first (from the body), then the three bumps in chronological
    // order. The two non-bump comments are dropped.
    assert.deepEqual(
      series,
      [
        { hitCount: 83, at: "2026-06-28T11:33:19Z" },
        { hitCount: 150, at: "2026-07-24T23:16:03Z" },
        { hitCount: 160, at: "2026-07-30T04:45:17Z" },
        { hitCount: 200, at: "2026-08-08T11:41:32Z" },
      ],
    );
  });

  test("parseEscalationBumpSeries: empty array when nothing parses (caller fails open)", () => {
    assert.deepEqual(
      parseEscalationBumpSeries("no hit count here", "2026-07-01T00:00:00Z", []),
      [],
    );
    // A non-escalation comment with no "now N hits" phrase contributes nothing.
    assert.deepEqual(
      parseEscalationBumpSeries("no body hits", "2026-07-01T00:00:00Z", [
        { body: "operator review prose", createdAt: "2026-07-02T00:00:00Z" },
      ]),
      [],
    );
  });

  test("parseEscalationBumpSeries: body fallback via '**Hit count:** N' when the prefix drifted", () => {
    const body = "Some other wording.\n\n**Hit count:** 42";
    const series = parseEscalationBumpSeries(body, "2026-07-01T00:00:00Z", []);
    assert.deepEqual(series, [{ hitCount: 42, at: "2026-07-01T00:00:00Z" }]);
  });

  // -------------------------------------------------------------------------
  // shouldRateEscalate — the pure decision
  // -------------------------------------------------------------------------

  test("shouldRateEscalate: empty series fails open (post)", () => {
    assert.equal(shouldRateEscalate([], 200, isoFromNow(0)), true);
  });

  test("shouldRateEscalate: only creation, within window → suppress", () => {
    const series = [{ hitCount: 150, at: isoFromNow(-2) }]; // created 2 days ago
    assert.equal(shouldRateEscalate(series, 160, isoFromNow(0)), false);
  });

  test("shouldRateEscalate: only creation, past window → post (first post-creation bump)", () => {
    const series = [{ hitCount: 150, at: isoFromNow(-30) }]; // created 30 days ago
    // First windowed bump attempt: no baseline yet → always posts.
    assert.equal(shouldRateEscalate(series, 160, isoFromNow(0)), true);
  });

  test("shouldRateEscalate: steady rate (recent ≈ baseline) → suppress", () => {
    // creation@100 60d ago, bump@160 30d ago: baseline = 60/30 = 2.0/day.
    // current 220: recent = 60/30 = 2.0/day. 2.0 < 2.0*1.5=3.0 → suppress.
    const series = [
      { hitCount: 100, at: isoFromNow(-60) },
      { hitCount: 160, at: isoFromNow(-30) },
    ];
    assert.equal(shouldRateEscalate(series, 220, isoFromNow(0)), false);
  });

  test("shouldRateEscalate: rising rate (recent >= baseline*1.5) → post", () => {
    // creation@100 60d ago, bump@130 30d ago: baseline = 30/30 = 1.0/day.
    // current 220: recent = 90/30 = 3.0/day. 3.0 >= 1.0*1.5=1.5 → post.
    const series = [
      { hitCount: 100, at: isoFromNow(-60) },
      { hitCount: 130, at: isoFromNow(-30) },
    ];
    assert.equal(shouldRateEscalate(series, 220, isoFromNow(0)), true);
  });

  test("shouldRateEscalate: within window of the last bump → suppress regardless of rate", () => {
    // A bursty 2-day-old bump must not trip the gate even if the rate spiked.
    const series = [
      { hitCount: 100, at: isoFromNow(-60) },
      { hitCount: 160, at: isoFromNow(-2) },
    ];
    assert.equal(shouldRateEscalate(series, 300, isoFromNow(0)), false);
  });

  test("shouldRateEscalate: recent rate just under the bar → suppress (boundary)", () => {
    // baseline = 60/30 = 2.0/day; bar = 3.0/day. recent = 89/30 = 2.967 < 3.0.
    const series = [
      { hitCount: 100, at: isoFromNow(-60) },
      { hitCount: 160, at: isoFromNow(-30) },
    ];
    assert.equal(shouldRateEscalate(series, 249, isoFromNow(0)), false);
    // One more hit clears it: 90/30 = 3.0 >= 3.0 → post.
    assert.equal(shouldRateEscalate(series, 250, isoFromNow(0)), true);
  });

  // -------------------------------------------------------------------------
  // Real-data replay — the empirical justification for WINDOW=7, MULTIPLIER=1.5
  // -------------------------------------------------------------------------

  test("REAL #2528 replay: only the first post-creation bump posts across the steady series", () => {
    // The actual escalation history of acceptance-criterion-unmet on #2528:
    // issue body @ 83 hits (2026-06-28); escalation-bump comments at
    // 150/160/170/180/190/200. Simulate the gate deciding each +10 intent in
    // turn. It observes the creation point first; a posted bump is appended to
    // the observed series and becomes the next baseline anchor; a suppressed
    // bump writes nothing (zero GitHub-side writes), so the anchor holds.
    const intents = [
      { hit: 150, now: "2026-07-24T23:16:03Z" },
      { hit: 160, now: "2026-07-30T04:45:17Z" },
      { hit: 170, now: "2026-07-31T01:32:01Z" },
      { hit: 180, now: "2026-08-01T12:36:43Z" },
      { hit: 190, now: "2026-08-06T10:48:41Z" },
      { hit: 200, now: "2026-08-08T11:41:32Z" },
    ];
    const series = [{ hitCount: 83, at: "2026-06-28T11:33:19Z" }]; // creation (issue body)
    const posted: number[] = [];
    for (const intent of intents) {
      if (shouldRateEscalate(series, intent.hit, intent.now)) {
        posted.push(intent.hit);
        series.push({ hitCount: intent.hit, at: intent.now });
      }
    }
    // The gate posts 150 (the first post-creation attempt after the 7-day
    // window) and 180 (a GENUINE burst: 160→170→180 arrived within ~2.5 days,
    // ~4/day vs the ~2.5/day baseline — exactly the rising-rate signal an
    // operator wants). It suppresses 160/170 (window not yet met) and 190/200
    // (window not yet met since the 180 bump). So 2 bumps over eight days vs
    // the old count gate's six (150→160→170→180→190→200) — within the
    // design-concept's "0-2 escalations" claim, and the nag floor is gone.
    assert.deepEqual(posted, [150, 180]);
  });

  test("REAL #2528 series extended with a sustained doubling re-escalates", () => {
    // Continue from the steady series: the first post-creation bump (150) has
    // posted, so the baseline is ~2.5/day. Now the rate DOUBLES and HOLDS
    // (+10 every ~2 days ≈ 5/day). The gate must still surface a genuinely
    // rising rate once the higher rate dominates the window average — the aim
    // is to remove the floor of permanent nagging, NOT to mute the signal.
    const series = [
      { hitCount: 83, at: "2026-06-28T11:33:19Z" },
      { hitCount: 150, at: "2026-07-24T23:16:03Z" },
    ];
    const doubled = [
      { hit: 210, now: "2026-08-10T11:41:32Z" },
      { hit: 220, now: "2026-08-12T11:41:32Z" },
      { hit: 230, now: "2026-08-14T11:41:32Z" },
      { hit: 240, now: "2026-08-16T11:41:32Z" },
    ];
    let posted = -1;
    for (const intent of doubled) {
      if (shouldRateEscalate(series, intent.hit, intent.now)) {
        posted = intent.hit;
        break;
      }
    }
    assert.ok(posted > 0, "a sustained doubling must re-escalate, not be muted");
  });

  // -------------------------------------------------------------------------
  // Issue #4073 — the SAME shouldRateEscalate math now also gates the
  // CLOSED→reopen path (escalation.ts wires it in verbatim; no new algorithm).
  // This replays #2528's OWN reopen-cycle evidence — the four real
  // pre-#4073 reopens (issue #4073's timeline table: 160/190/200/210 hits at
  // 2026-07-30 / 08-06 / 08-08 / 08-14) that happened precisely because the
  // reopen path was ungated and every post-close recurrence fired
  // unconditionally.
  // -------------------------------------------------------------------------

  test("REAL #2528 reopen-cycle replay: the gate suppresses later post-close recurrences (issue #4073)", () => {
    // Before #4073 all four of these reopened unconditionally (the issue's
    // own evidence table: four cycles in 15 days, none of which ever reached
    // the #3850 gate). Replaying the same real (hitCount, timestamp) pairs
    // through the shared shouldRateEscalate function — now wired into the
    // CLOSED→reopen branch too — cuts that to two: the near-week gap to 190
    // still reads as a genuine acceleration and reopens, but the tighter
    // 200/210 follow-ups fall back inside the (now-later) anchor's window /
    // below its rate and are suppressed, exactly the "reopen is suppressed
    // at [subsequent] steps" fix the issue asks for.
    const attempts = [
      { hit: 160, now: "2026-07-30T04:45:17Z" },
      { hit: 190, now: "2026-08-06T10:48:41Z" },
      { hit: 200, now: "2026-08-08T11:41:32Z" },
      { hit: 210, now: "2026-08-14T09:00:00Z" },
    ];
    const series = [{ hitCount: 83, at: "2026-06-28T11:33:19Z" }]; // creation (issue body)
    const posted: number[] = [];
    for (const a of attempts) {
      if (shouldRateEscalate(series, a.hit, a.now)) {
        posted.push(a.hit);
        series.push({ hitCount: a.hit, at: a.now });
      }
    }
    assert.deepEqual(posted, [160, 190]);
    assert.ok(
      !posted.includes(200) && !posted.includes(210),
      "the follow-up 200/210 recurrences must be suppressed, not reopen unconditionally as they did pre-#4073",
    );
  });
});

// ===========================================================================
// 2. Integration (escalation.ts) via a fake gh
// ===========================================================================

describe("rate-gate escalation integration (escalation.ts, issue #3850)", () => {
  let workDir: string;
  let fakeGhPath: string;
  let invocationsPath: string;
  let historyPath: string;

  let originalGhBin: string | undefined;
  let originalDisabled: string | undefined;
  let originalRepo: string | undefined;

  let escalatePatternToIssue: typeof import("../src/pattern-memory/escalation.ts").escalatePatternToIssue;

  /**
   * The fake gh dispatches by sub-command:
   *   issue list   → one OPEN issue (number 4242) whose title contains the cue
   *   issue view   → the JSON history staged at $FAKE_GH_HISTORY_FILE (or a
   *                  default steady-rate history); fails when FAKE_GH_VIEW_FAILS=1
   *   issue comment→ success (logged so the test can assert it ran / didn't)
   *   label        → success
   */
  async function writeFakeGh(path: string) {
    const body = `#!/usr/bin/env bash
set -u
LOGFILE="\${FAKE_GH_INVOCATIONS_LOG}"
printf '%s\\n' "$(printf '%s ' "$@")" >> "$LOGFILE"

CMD="\${1:-}"; SUBCMD="\${2:-}"

if [ "$CMD" = "issue" ] && [ "$SUBCMD" = "list" ]; then
  STATE="\${FAKE_GH_LIST_STATE:-OPEN}"
  CUE="\${FAKE_GH_LIST_CUE:-acceptance-criterion-unmet}"
  echo '[{"number": 4242, "state": "'"$STATE"'", "title": "meta(lesson): '"$CUE"' hit 150 times across hydra-qa"}]'
  exit 0
fi

if [ "$CMD" = "issue" ] && [ "$SUBCMD" = "view" ]; then
  if [ "\${FAKE_GH_VIEW_FAILS:-0}" = "1" ]; then
    echo "fake gh: simulated view failure" >&2
    exit 1
  fi
  if [ -n "\${FAKE_GH_HISTORY_FILE:-}" ] && [ -f "\${FAKE_GH_HISTORY_FILE:-}" ]; then
    cat "\${FAKE_GH_HISTORY_FILE}"
  else
    echo '{"createdAt":"2026-07-01T00:00:00Z","body":"Auto-escalated by the learning system after 150 hits on cue \`acceptance-criterion-unmet\`.","comments":[]}'
  fi
  exit 0
fi

if [ "$CMD" = "issue" ] && [ "$SUBCMD" = "comment" ]; then
  echo "https://github.com/gaberoo322/hydra/issues/4242#issuecomment-1"
  exit 0
fi

if [ "$CMD" = "label" ]; then
  exit 0
fi

exit 0
`;
    await writeFile(path, body, "utf-8");
    await chmod(path, 0o755);
  }

  async function readInvocations(): Promise<string[]> {
    if (!existsSync(invocationsPath)) return [];
    const raw = await readFile(invocationsPath, "utf-8");
    return raw.split("\n").filter(l => l.trim().length > 0);
  }

  /** Stage an issue history (creation body + bump comments) to the fake gh. */
  async function stageHistory(body: string, createdAt: string, comments: Array<{ body: string; createdAt: string }>) {
    await writeFile(historyPath, JSON.stringify({ createdAt, body, comments }), "utf-8");
    process.env.FAKE_GH_HISTORY_FILE = historyPath;
  }

  before(async () => {
    workDir = await mkdtemp(join(tmpdir(), "hydra-rate-gate-"));
    await mkdir(workDir, { recursive: true });
    fakeGhPath = join(workDir, "fake-gh");
    invocationsPath = join(workDir, "invocations.log");
    historyPath = join(workDir, "history.json");
    await writeFakeGh(fakeGhPath);

    originalGhBin = process.env.HYDRA_GH_BIN;
    originalDisabled = process.env.HYDRA_ESCALATION_DISABLED;
    originalRepo = process.env.HYDRA_GH_REPO;
    process.env.HYDRA_GH_BIN = fakeGhPath;
    process.env.HYDRA_GH_REPO = "gaberoo322/hydra";
    process.env.FAKE_GH_INVOCATIONS_LOG = invocationsPath;
    delete process.env.HYDRA_ESCALATION_DISABLED;

    const mod = await import("../src/pattern-memory/escalation.ts");
    escalatePatternToIssue = mod.escalatePatternToIssue;
  });

  beforeEach(async () => {
    await writeFile(invocationsPath, "", "utf-8");
    delete process.env.FAKE_GH_VIEW_FAILS;
    delete process.env.FAKE_GH_HISTORY_FILE;
    delete process.env.FAKE_GH_LIST_STATE;
    delete process.env.FAKE_GH_LIST_CUE;
  });

  after(async () => {
    if (originalGhBin === undefined) delete process.env.HYDRA_GH_BIN;
    else process.env.HYDRA_GH_BIN = originalGhBin;
    if (originalDisabled === undefined) delete process.env.HYDRA_ESCALATION_DISABLED;
    else process.env.HYDRA_ESCALATION_DISABLED = originalDisabled;
    if (originalRepo === undefined) delete process.env.HYDRA_GH_REPO;
    else process.env.HYDRA_GH_REPO = originalRepo;
    delete process.env.FAKE_GH_INVOCATIONS_LOG;
    delete process.env.FAKE_GH_VIEW_FAILS;
    delete process.env.FAKE_GH_HISTORY_FILE;
    delete process.env.FAKE_GH_LIST_STATE;
    delete process.env.FAKE_GH_LIST_CUE;
    await rm(workDir, { recursive: true, force: true });
  });

  const input = (hitCount: number) => ({
    kind: "lesson" as const,
    cue: "acceptance-criterion-unmet",
    hitCount,
    skills: ["hydra-qa"],
    lastReference: "issue-3850",
  });

  test("steady-rate OPEN issue → status=skipped, NO comment written", async () => {
    // creation@100 60d ago, bump@160 30d ago (baseline 2.0/day); current 220
    // (recent 2.0/day < 3.0/day bar). Window met, rate steady → suppress.
    await stageHistory(
      "Auto-escalated by the learning system after 100 hits on cue `acceptance-criterion-unmet`.",
      isoFromNow(-60),
      [{ body: "Pattern still firing — now 160 hits on `acceptance-criterion-unmet`.", createdAt: isoFromNow(-30) }],
    );
    const result = await escalatePatternToIssue(input(220));
    assert.equal(result.status, "skipped");
    const invocations = await readInvocations();
    assert.ok(
      !invocations.some(l => l.startsWith("issue comment ")),
      "a rate-gated steady-rate bump must NOT post a comment",
    );
    assert.ok(
      invocations.some(l => l.startsWith("issue view ")),
      "the gate must fetch the issue history before deciding",
    );
  });

  test("rising-rate OPEN issue → status=commented (signal still reaches operator)", async () => {
    // creation@100 60d ago, bump@130 30d ago (baseline 1.0/day); current 220
    // (recent 3.0/day >= 1.5/day bar) → post.
    await stageHistory(
      "Auto-escalated by the learning system after 100 hits on cue `acceptance-criterion-unmet`.",
      isoFromNow(-60),
      [{ body: "Pattern still firing — now 130 hits on `acceptance-criterion-unmet`.", createdAt: isoFromNow(-30) }],
    );
    const result = await escalatePatternToIssue(input(220));
    assert.equal(result.status, "commented");
    if (result.status === "commented") assert.equal(result.issueNumber, 4242);
    const invocations = await readInvocations();
    assert.ok(invocations.some(l => l.startsWith("issue comment 4242")), "expected a comment-bump");
  });

  test("within-window bump → status=skipped even if the rate spiked", async () => {
    // Most-recent bump only 2 days ago → window not met → suppress.
    await stageHistory(
      "Auto-escalated by the learning system after 100 hits on cue `acceptance-criterion-unmet`.",
      isoFromNow(-60),
      [{ body: "Pattern still firing — now 160 hits on `acceptance-criterion-unmet`.", createdAt: isoFromNow(-2) }],
    );
    const result = await escalatePatternToIssue(input(300));
    assert.equal(result.status, "skipped");
    const invocations = await readInvocations();
    assert.ok(!invocations.some(l => l.startsWith("issue comment ")), "window-not-met must suppress");
  });

  test("first post-creation bump (window met, no baseline) → status=commented", async () => {
    // Issue created 30d ago at 150 hits, NO bump comments yet → first
    // post-creation bump attempt past the window always posts.
    await stageHistory(
      "Auto-escalated by the learning system after 150 hits on cue `acceptance-criterion-unmet`.",
      isoFromNow(-30),
      [],
    );
    const result = await escalatePatternToIssue(input(160));
    assert.equal(result.status, "commented");
  });

  test("gh history-fetch failure → fail OPEN (status=commented)", async () => {
    // A transient gh/auth/rate-limit failure on the view call must NOT suppress
    // a possibly-genuine rising-rate signal — degrade to the unconditional bump.
    process.env.FAKE_GH_VIEW_FAILS = "1";
    const result = await escalatePatternToIssue(input(220));
    assert.equal(result.status, "commented");
    const invocations = await readInvocations();
    assert.ok(invocations.some(l => l.startsWith("issue comment 4242")), "fetch failure must fail-open to a comment");
  });

  test("non-rate-gated cue → unchanged: OPEN issue bumps unconditionally (no view fetched)", async () => {
    // An ordinary low-rate cue is NOT in RATE_GATED_CUES, so the gate is never
    // entered — no `issue view` fetch, and the comment posts as before #3850.
    process.env.FAKE_GH_LIST_CUE = "stale-local-master-ref";
    const result = await escalatePatternToIssue({
      kind: "friction",
      cue: "stale-local-master-ref",
      hitCount: 13,
      skills: ["hydra-dev"],
    });
    assert.equal(result.status, "commented");
    const invocations = await readInvocations();
    assert.ok(
      !invocations.some(l => l.startsWith("issue view ")),
      "non-rate-gated cues must NOT trigger a history fetch",
    );
    assert.ok(invocations.some(l => l.startsWith("issue comment 4242")), "expected an unconditional comment-bump");
  });

  // -------------------------------------------------------------------------
  // Issue #4073 — the CLOSED→reopen path is now gated too, for rate-gated
  // cues. Before #4073 ANY post-close recurrence reopened unconditionally;
  // for a steady-rate cue that guarantees a reopen within days of every
  // close, which routes the next hit around the OPEN-path gate entirely
  // (issue #2528's four-cycles-in-15-days evidence). This replaces the old
  // "reopen path is NEVER rate-gated" test, which pinned exactly that defect.
  // -------------------------------------------------------------------------

  test("closed issue, steady rate (rate-gated cue) → status=skipped, NO reopen, NO comment", async () => {
    // creation@100 60d ago, bump@160 30d ago (baseline 2.0/day); current 220
    // (recent 2.0/day < 3.0/day bar). Window met, rate steady → the CLOSED
    // issue stays closed, mirroring the OPEN-path steady-rate suppression.
    process.env.FAKE_GH_LIST_STATE = "CLOSED";
    await stageHistory(
      "Auto-escalated by the learning system after 100 hits on cue `acceptance-criterion-unmet`.",
      isoFromNow(-60),
      [{ body: "Pattern still firing — now 160 hits on `acceptance-criterion-unmet`.", createdAt: isoFromNow(-30) }],
    );
    const result = await escalatePatternToIssue(input(220));
    assert.equal(result.status, "skipped");
    const invocations = await readInvocations();
    assert.ok(invocations.some(l => l.startsWith("issue view ")), "the gate must fetch history before deciding");
    assert.ok(!invocations.some(l => l.startsWith("issue reopen ")), "a steady-rate cue must NOT reopen");
    assert.ok(!invocations.some(l => l.startsWith("issue comment ")), "a steady-rate cue must NOT comment");
  });

  test("closed issue, rising rate (rate-gated cue) → reopens, comments, and re-applies a lifecycle label", async () => {
    // creation@100 60d ago, bump@130 30d ago (baseline 1.0/day); current 220
    // (recent 3.0/day >= 1.5/day bar) → the genuine rising-rate signal still
    // reaches the operator via a reopen.
    process.env.FAKE_GH_LIST_STATE = "CLOSED";
    await stageHistory(
      "Auto-escalated by the learning system after 100 hits on cue `acceptance-criterion-unmet`.",
      isoFromNow(-60),
      [{ body: "Pattern still firing — now 130 hits on `acceptance-criterion-unmet`.", createdAt: isoFromNow(-30) }],
    );
    const result = await escalatePatternToIssue(input(220));
    assert.equal(result.status, "reopened");
    if (result.status === "reopened") assert.equal(result.issueNumber, 4242);
    const invocations = await readInvocations();
    assert.ok(invocations.some(l => l.startsWith("issue view ")), "the gate must fetch history before deciding");
    assert.ok(invocations.some(l => l.startsWith("issue reopen 4242")), "expected reopen on a rising-rate close");
    assert.ok(invocations.some(l => l.startsWith("issue comment 4242")), "expected a comment after reopen");
    assert.ok(
      invocations.some(l => l.startsWith("issue edit 4242") && l.includes("--add-label") && l.includes("ready-for-human")),
      "expected a lifecycle label re-applied after reopen (issue #4073)",
    );
  });

  test("closed issue, gh history-fetch failure → fail OPEN (reopens unconditionally)", async () => {
    // Same fail-open contract as the OPEN-path gate: a transient gh/auth/
    // rate-limit failure on the view call must NOT suppress a possibly-
    // genuine recurrence — degrade to the unconditional reopen.
    process.env.FAKE_GH_LIST_STATE = "CLOSED";
    process.env.FAKE_GH_VIEW_FAILS = "1";
    const result = await escalatePatternToIssue(input(220));
    assert.equal(result.status, "reopened");
    const invocations = await readInvocations();
    assert.ok(invocations.some(l => l.startsWith("issue reopen 4242")), "fetch failure must fail-open to a reopen");
    assert.ok(invocations.some(l => l.startsWith("issue comment 4242")));
  });

  test("closed issue, non-rate-gated cue → reopens unconditionally, no history fetch, still gets a lifecycle label", async () => {
    // Ordinary cues are NOT in RATE_GATED_CUES, so the CLOSED→reopen gate is
    // never entered — no `issue view` fetch, and the reopen is unconditional,
    // exactly as before #4073. The lifecycle-label re-apply, however, is NOT
    // cue-specific — it fires on every reopen that proceeds.
    process.env.FAKE_GH_LIST_STATE = "CLOSED";
    process.env.FAKE_GH_LIST_CUE = "stale-local-master-ref";
    const result = await escalatePatternToIssue({
      kind: "friction",
      cue: "stale-local-master-ref",
      hitCount: 13,
      skills: ["hydra-dev"],
    });
    assert.equal(result.status, "reopened");
    const invocations = await readInvocations();
    assert.ok(
      !invocations.some(l => l.startsWith("issue view ")),
      "non-rate-gated cues must NOT trigger a history fetch on the reopen path",
    );
    assert.ok(invocations.some(l => l.startsWith("issue reopen 4242")), "expected an unconditional reopen");
    assert.ok(
      invocations.some(l => l.startsWith("issue edit 4242") && l.includes("--add-label") && l.includes("ready-for-human")),
      "expected a lifecycle label re-applied after reopen even for a non-rate-gated cue",
    );
  });
});
