/**
 * Regression tests for the wire-or-retire emit planner — step 4 of the Target
 * dead-code cleanup plan, the JUDGMENT half of /hydra-target-cleanup.
 *
 * What the planner must guarantee:
 *
 *   1. LEDGER-DRIVEN: input is the Target's committed wiring-status ledger
 *      (canonical table rendered by hydra-betting's renderWiringLedger); only
 *      `wire-or-retire` rows are eligible — awaiting-wiring and
 *      protected-provider rows never become items.
 *   2. TRIAGE ROUTING: items are decision items, not deletion orders — the
 *      body carries the wire/retire/unclear protocol and the unclear branch
 *      routes to ready-for-human, never deletion (fail closed).
 *   3. DEDUP + CAP: one open item per module path; at most
 *      WIRE_OR_RETIRE_EMIT_CAP per run, oldest last-touched first.
 *   4. TITLE/BODY COHERENCE: title and body for an item come from the same
 *      ledger row in one pass (the #1449/#1005 drift guard).
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import {
  parseLedger,
  planWireOrRetireEmit,
  renderWireOrRetireTitle,
  identityFromOpenItemTitle,
  WIRE_OR_RETIRE_EMIT_CAP,
} from "../scripts/ci/hydra-target-wire-or-retire-emit.ts";

/** A ledger fragment in the canonical renderWiringLedger table format. */
const LEDGER = `# Wiring status — production modules unreachable from runtime

> Generated by \`npm run deadcode:ledger\` on 2026-06-10.

**5 modules**: 3 wire-or-retire · 1 awaiting-wiring · 1 protected-provider

| Module | Status | Imported by | Last touched |
|---|---|---|---|
| \`web/src/lib/markets/no-vig.ts\` | wire-or-retire | nothing (orphan) | 2026-04-17 |
| \`web/src/lib/markets/ingestion.ts\` | wire-or-retire | other unreachable modules | 2026-04-03 |
| \`web/src/lib/markets/scanner-replay.ts\` | wire-or-retire | tests only | 2026-04-14 |
| \`web/src/lib/fresh.ts\` | awaiting-wiring | tests only | 2026-06-01 |
| \`web/src/lib/providers/venue.ts\` | protected-provider | tests only | 2026-04-01 |
`;

describe("parseLedger", () => {
  test("parses the canonical table rows", () => {
    const rows = parseLedger(LEDGER);
    assert.equal(rows.length, 5);
    assert.deepEqual(rows[0], {
      path: "web/src/lib/markets/no-vig.ts",
      status: "wire-or-retire",
      importedBy: "nothing (orphan)",
      lastTouched: "2026-04-17",
    });
  });

  test("skips non-table and malformed lines rather than guessing", () => {
    const rows = parseLedger("# heading\n\nprose | with | pipes\n| not-backticked | x | y | z |\n");
    assert.equal(rows.length, 0);
  });
});

describe("planWireOrRetireEmit — eligibility", () => {
  test("emits only wire-or-retire rows; awaiting-wiring and protected-provider never become items", () => {
    const plan = planWireOrRetireEmit(LEDGER, [], "2026-06-10");
    assert.equal(plan.eligibleCount, 3);
    assert.equal(plan.items.length, 3);
    const paths = plan.items.map((i) => i.row.path);
    assert.ok(!paths.includes("web/src/lib/fresh.ts"), "awaiting-wiring must not be emitted");
    assert.ok(
      !paths.includes("web/src/lib/providers/venue.ts"),
      "protected-provider must not be emitted",
    );
  });

  test("orders oldest last-touched first", () => {
    const plan = planWireOrRetireEmit(LEDGER, [], "2026-06-10");
    assert.deepEqual(
      plan.items.map((i) => i.row.lastTouched),
      ["2026-04-03", "2026-04-14", "2026-04-17"],
    );
  });
});

describe("planWireOrRetireEmit — dedup and cap", () => {
  test("a module with an open wire-or-retire item is not re-filed", () => {
    const open = renderWireOrRetireTitle("web/src/lib/markets/no-vig.ts");
    const plan = planWireOrRetireEmit(LEDGER, [open], "2026-06-10");
    assert.equal(plan.items.length, 2);
    assert.equal(plan.dropped.length, 1);
    assert.match(plan.dropped[0].reason, /already covers/);
  });

  test("identityFromOpenItemTitle round-trips rendered titles", () => {
    assert.equal(
      identityFromOpenItemTitle(renderWireOrRetireTitle("web/src/lib/a.ts")),
      "web/src/lib/a.ts",
    );
    assert.equal(identityFromOpenItemTitle("cleanup(target): demote `x` in src/lib/a.ts"), null);
    assert.equal(identityFromOpenItemTitle("feat: unrelated"), null);
  });

  test(`caps at ${WIRE_OR_RETIRE_EMIT_CAP} items per run`, () => {
    const manyRows = Array.from(
      { length: WIRE_OR_RETIRE_EMIT_CAP + 2 },
      (_, i) =>
        `| \`web/src/lib/mod-${i}.ts\` | wire-or-retire | tests only | 2026-04-0${i + 1} |`,
    ).join("\n");
    const ledger = `| Module | Status | Imported by | Last touched |\n|---|---|---|---|\n${manyRows}\n`;
    const plan = planWireOrRetireEmit(ledger, [], "2026-06-10");
    assert.equal(plan.items.length, WIRE_OR_RETIRE_EMIT_CAP);
    assert.equal(
      plan.dropped.filter((d) => /over the per-run cap/.test(d.reason)).length,
      2,
    );
  });
});

describe("rendering — decision protocol and coherence", () => {
  const plan = planWireOrRetireEmit(LEDGER, [], "2026-06-10");
  const item = plan.items.find((i) => i.row.path === "web/src/lib/markets/no-vig.ts")!;

  test("title and body name the same module (the drift guard)", () => {
    assert.match(item.title, /web\/src\/lib\/markets\/no-vig\.ts/);
    assert.match(item.body, /# cleanup\(target\): wire-or-retire `web\/src\/lib\/markets\/no-vig\.ts`/);
    assert.match(item.body, /- `web\/src\/lib\/markets\/no-vig\.ts`/);
  });

  test("body carries the three-way decision protocol with fail-closed ambiguity", () => {
    assert.match(item.body, /\*\*\(a\) WIRE\*\*/);
    assert.match(item.body, /\*\*\(b\) RETIRE\*\*/);
    assert.match(item.body, /\*\*\(c\) UNCLEAR\*\*/);
    assert.match(item.body, /ready-for-human/);
    assert.match(item.body, /Ambiguity never resolves to deletion/);
    assert.match(item.body, /scan date 2026-06-10/);
  });

  test("body instructs verify-first against ledger staleness", () => {
    assert.match(item.body, /\*\*Verify first\*\*/);
    assert.match(item.body, /close this item as stale/);
  });

  test("body forbids deletion while the item is in triage", () => {
    assert.match(item.body, /do NOT delete anything while it sits in triage/);
  });

  test("renderWireOrRetireTitle throws on an empty path (blank-title guard)", () => {
    assert.throws(() => renderWireOrRetireTitle("  "));
  });
});
