/**
 * Regression tests for the wire-or-retire emit planner — step 4 of the Target
 * dead-code cleanup plan, the JUDGMENT half of /hydra-target-cleanup.
 *
 * What the planner must guarantee:
 *
 *   1. LEDGER-DRIVEN: input is the Target's committed wiring-status ledger
 *      (canonical table rendered by hydra-betting's renderWiringLedger); only
 *      `wire-or-retire` rows are eligible — awaiting-wiring and
 *      protected-provider rows never become items.
 *   2. TRIAGE ROUTING: items are decision items, not deletion orders — the
 *      body carries the wire/retire/unclear protocol and the unclear branch
 *      routes to ready-for-human, never deletion (fail closed).
 *   3. DEDUP + CAP: one open item per module path; at most
 *      WIRE_OR_RETIRE_EMIT_CAP per run, oldest last-touched first.
 *   4. TITLE/BODY COHERENCE: title and body for an item come from the same
 *      ledger row in one pass (the #1449/#1005 drift guard).
 */

import { test, describe, afterEach } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  parseLedger,
  planWireOrRetireEmit,
  renderWireOrRetireTitle,
  identityFromOpenItemTitle,
  WIRE_OR_RETIRE_EMIT_CAP,
  decideLedgerSkip,
  buildWireOrRetireShellSpec,
  resolveWireOrRetireTargetInputs,
  ledgerPathForWorkspace,
} from "../scripts/ci/hydra-target-wire-or-retire-emit.ts";
import { __resetForTests as resetTargetConfig } from "../src/target-config.ts";

const EMIT_SOURCE_PATH = fileURLToPath(
  new URL("../scripts/ci/hydra-target-wire-or-retire-emit.ts", import.meta.url),
);

/** A ledger fragment in the canonical renderWiringLedger table format. */
const LEDGER = `# Wiring status — production modules unreachable from runtime

> Generated by \`npm run deadcode:ledger\` on 2026-06-10.

**5 modules**: 3 wire-or-retire · 1 awaiting-wiring · 1 protected-provider

| Module | Status | Imported by | Last touched |
|---|---|---|---|
| \`web/src/lib/markets/no-vig.ts\` | wire-or-retire | nothing (orphan) | 2026-04-17 |
| \`web/src/lib/markets/ingestion.ts\` | wire-or-retire | other unreachable modules | 2026-04-03 |
| \`web/src/lib/markets/scanner-replay.ts\` | wire-or-retire | tests only | 2026-04-14 |
| \`web/src/lib/fresh.ts\` | awaiting-wiring | tests only | 2026-06-01 |
| \`web/src/lib/providers/venue.ts\` | protected-provider | tests only | 2026-04-01 |
`;

describe("parseLedger", () => {
  test("parses the canonical table rows", () => {
    const rows = parseLedger(LEDGER);
    assert.equal(rows.length, 5);
    assert.deepEqual(rows[0], {
      path: "web/src/lib/markets/no-vig.ts",
      status: "wire-or-retire",
      importedBy: "nothing (orphan)",
      lastTouched: "2026-04-17",
    });
  });

  test("skips non-table and malformed lines rather than guessing", () => {
    const rows = parseLedger("# heading\n\nprose | with | pipes\n| not-backticked | x | y | z |\n");
    assert.equal(rows.length, 0);
  });
});

describe("planWireOrRetireEmit — eligibility", () => {
  test("emits only wire-or-retire rows; awaiting-wiring and protected-provider never become items", () => {
    const plan = planWireOrRetireEmit(LEDGER, [], "2026-06-10");
    assert.equal(plan.eligibleCount, 3);
    assert.equal(plan.items.length, 3);
    const paths = plan.items.map((i) => i.row.path);
    assert.ok(!paths.includes("web/src/lib/fresh.ts"), "awaiting-wiring must not be emitted");
    assert.ok(
      !paths.includes("web/src/lib/providers/venue.ts"),
      "protected-provider must not be emitted",
    );
  });

  test("orders oldest last-touched first", () => {
    const plan = planWireOrRetireEmit(LEDGER, [], "2026-06-10");
    assert.deepEqual(
      plan.items.map((i) => i.row.lastTouched),
      ["2026-04-03", "2026-04-14", "2026-04-17"],
    );
  });
});

describe("planWireOrRetireEmit — dedup and cap", () => {
  test("a module with an open wire-or-retire item is not re-filed", () => {
    const open = renderWireOrRetireTitle("web/src/lib/markets/no-vig.ts");
    const plan = planWireOrRetireEmit(LEDGER, [open], "2026-06-10");
    assert.equal(plan.items.length, 2);
    assert.equal(plan.dropped.length, 1);
    assert.match(plan.dropped[0].reason, /already covers/);
  });

  test("identityFromOpenItemTitle round-trips rendered titles", () => {
    assert.equal(
      identityFromOpenItemTitle(renderWireOrRetireTitle("web/src/lib/a.ts")),
      "web/src/lib/a.ts",
    );
    assert.equal(identityFromOpenItemTitle("cleanup(target): demote `x` in src/lib/a.ts"), null);
    assert.equal(identityFromOpenItemTitle("feat: unrelated"), null);
  });

  test(`caps at ${WIRE_OR_RETIRE_EMIT_CAP} items per run`, () => {
    const manyRows = Array.from(
      { length: WIRE_OR_RETIRE_EMIT_CAP + 2 },
      (_, i) =>
        `| \`web/src/lib/mod-${i}.ts\` | wire-or-retire | tests only | 2026-04-0${i + 1} |`,
    ).join("\n");
    const ledger = `| Module | Status | Imported by | Last touched |\n|---|---|---|---|\n${manyRows}\n`;
    const plan = planWireOrRetireEmit(ledger, [], "2026-06-10");
    assert.equal(plan.items.length, WIRE_OR_RETIRE_EMIT_CAP);
    assert.equal(
      plan.dropped.filter((d) => /over the per-run cap/.test(d.reason)).length,
      2,
    );
  });
});

describe("rendering — decision protocol and coherence", () => {
  const plan = planWireOrRetireEmit(LEDGER, [], "2026-06-10");
  const item = plan.items.find((i) => i.row.path === "web/src/lib/markets/no-vig.ts")!;

  test("title and body name the same module (the drift guard)", () => {
    assert.match(item.title, /web\/src\/lib\/markets\/no-vig\.ts/);
    assert.match(item.body, /# cleanup\(target\): wire-or-retire `web\/src\/lib\/markets\/no-vig\.ts`/);
    assert.match(item.body, /- `web\/src\/lib\/markets\/no-vig\.ts`/);
  });

  test("body carries the three-way decision protocol with fail-closed ambiguity", () => {
    assert.match(item.body, /\*\*\(a\) WIRE\*\*/);
    assert.match(item.body, /\*\*\(b\) RETIRE\*\*/);
    assert.match(item.body, /\*\*\(c\) UNCLEAR\*\*/);
    assert.match(item.body, /ready-for-human/);
    assert.match(item.body, /Ambiguity never resolves to deletion/);
    assert.match(item.body, /scan date 2026-06-10/);
  });

  test("body instructs verify-first against ledger staleness", () => {
    assert.match(item.body, /\*\*Verify first\*\*/);
    assert.match(item.body, /close this item as stale/);
  });

  test("body forbids deletion while the item is in triage", () => {
    assert.match(item.body, /do NOT delete anything while it sits in triage/);
  });

  test("renderWireOrRetireTitle throws on an empty path (blank-title guard)", () => {
    assert.throws(() => renderWireOrRetireTitle("  "));
  });
});

// ---------------------------------------------------------------------------
// Target resolution through the target-config seam (issue #4553)
// ---------------------------------------------------------------------------

describe("wire-or-retire emit — Target resolved through the target-config seam (#4553)", () => {
  const saved = {
    ws: process.env.HYDRA_PROJECT_WORKSPACE,
    repo: process.env.HYDRA_TARGET_GITHUB_REPO,
  };
  afterEach(() => {
    if (saved.ws === undefined) delete process.env.HYDRA_PROJECT_WORKSPACE;
    else process.env.HYDRA_PROJECT_WORKSPACE = saved.ws;
    if (saved.repo === undefined) delete process.env.HYDRA_TARGET_GITHUB_REPO;
    else process.env.HYDRA_TARGET_GITHUB_REPO = saved.repo;
    resetTargetConfig();
  });

  test("resolves the ledger path and repo from HYDRA_PROJECT_WORKSPACE + HYDRA_TARGET_GITHUB_REPO", () => {
    resetTargetConfig();
    process.env.HYDRA_PROJECT_WORKSPACE = "/tmp/example-target-ws";
    process.env.HYDRA_TARGET_GITHUB_REPO = "example-owner/example-target";
    const inputs = resolveWireOrRetireTargetInputs();
    assert.equal(inputs.ledgerPath, "/tmp/example-target-ws/docs/agents/wiring-status.md");
    assert.equal(inputs.targetRepo, "example-owner/example-target");
    assert.ok(
      inputs.appPackageJsonPath.startsWith("/tmp/example-target-ws/"),
      `package.json probe must live under the resolved workspace; got ${inputs.appPackageJsonPath}`,
    );
    assert.ok(inputs.appPackageJsonPath.endsWith("/package.json"));
  });

  test("ledgerPathForWorkspace joins the fixed convention path and tolerates a trailing slash", () => {
    assert.equal(ledgerPathForWorkspace("/w/"), "/w/docs/agents/wiring-status.md");
    assert.equal(ledgerPathForWorkspace("/w"), "/w/docs/agents/wiring-status.md");
  });

  test("the shell spec defaults its source to the resolved ledger path", () => {
    const spec = buildWireOrRetireShellSpec({ ledgerPath: "/x/docs/agents/wiring-status.md", targetRepo: "o/r" });
    assert.equal(spec.defaultSourcePath, "/x/docs/agents/wiring-status.md");
  });

  test("the missing-ledger message names the resolved path and the deadcode:ledger convention, not hydra-betting", () => {
    const spec = buildWireOrRetireShellSpec({ ledgerPath: "/x/docs/agents/wiring-status.md", targetRepo: "o/r" });
    const msg = spec.missingSourceMessage("/x/docs/agents/wiring-status.md");
    assert.match(msg, /\/x\/docs\/agents\/wiring-status\.md/);
    assert.match(msg, /deadcode:ledger/);
    assert.doesNotMatch(msg, /hydra-betting/);
    assert.doesNotMatch(msg, /PR #98/);
  });

  test("the emit script source carries no hydra-betting identity literal and no removed constant exports", () => {
    const src = readFileSync(EMIT_SOURCE_PATH, "utf-8");
    assert.ok(!src.includes("/home/gabe/hydra-betting"), "no hardcoded Target workspace literal");
    assert.ok(!src.includes('"gaberoo322/hydra-betting"'), "no hardcoded Target repo literal");
    assert.ok(
      !/export const (TARGET_ROOT|LEDGER_FILE|TARGET_REPO)\b/.test(src),
      "TARGET_ROOT/LEDGER_FILE/TARGET_REPO must be removed",
    );
  });

  test("both gh calls use the same resolved targetRepo value", () => {
    const src = readFileSync(EMIT_SOURCE_PATH, "utf-8");
    const repoArgs = src.match(/"--repo",\s*\n\s*([A-Za-z_]+),/g) ?? [];
    assert.equal(repoArgs.length, 2, "exactly two gh --repo call sites");
    for (const m of repoArgs) assert.match(m, /targetRepo,$/);
  });

  test("importing the module resolves nothing at load time (no target-config fallback warning)", () => {
    const res = spawnSync(
      process.execPath,
      [
        "--experimental-strip-types",
        "--no-warnings",
        "--input-type=module",
        "-e",
        `await import(${JSON.stringify(EMIT_SOURCE_PATH)});`,
      ],
      {
        encoding: "utf-8",
        env: { ...process.env, HYDRA_PROJECT_WORKSPACE: "", HYDRA_TARGET_GITHUB_REPO: "", HYDRA_TARGET_NAME: "" },
      },
    );
    assert.equal(res.status, 0, `import must succeed; stderr: ${res.stderr}`);
    assert.doesNotMatch(res.stderr, /\[target-config\]/, `import must not resolve the Target; stderr: ${res.stderr}`);
  });
});

describe("decideLedgerSkip — ledgerless Target is a clean skip (#4553, mirrors #4531)", () => {
  const base = { explicitSourcePath: false, ledgerExists: false, ledgerPath: "/ws/docs/agents/wiring-status.md" };

  test("ledger absent and no deadcode:ledger script declared is a skip with one informational message", () => {
    const d = decideLedgerSkip({ ...base, appPackageJsonText: JSON.stringify({ scripts: { test: "x" } }) });
    assert.equal(d.skip, true);
    if (d.skip) {
      assert.match(d.message, /declares no wiring ledger/);
      assert.match(d.message, /nothing filed/);
    }
  });

  test("ledger absent with no or malformed package.json is a skip (positive evidence only)", () => {
    assert.equal(decideLedgerSkip({ ...base, appPackageJsonText: null }).skip, true);
    assert.equal(decideLedgerSkip({ ...base, appPackageJsonText: '{ "scripts": ' }).skip, true);
  });

  test("ledger absent but the generator IS declared is not a skip, so the shell fails loud", () => {
    const d = decideLedgerSkip({
      ...base,
      appPackageJsonText: JSON.stringify({ scripts: { "deadcode:ledger": "node gen.mjs" } }),
    });
    assert.equal(d.skip, false);
  });

  test("ledger present is not a skip", () => {
    assert.equal(decideLedgerSkip({ ...base, ledgerExists: true, appPackageJsonText: null }).skip, false);
  });

  test("an explicit positional source path bypasses the skip probe", () => {
    assert.equal(decideLedgerSkip({ ...base, explicitSourcePath: true, appPackageJsonText: null }).skip, false);
  });
});
