/**
 * test/seam-check-lib.test.mts — pin the shared baseline-ratchet engine behind
 * the four CI Seam checks (issue #950). The four per-Seam test files keep
 * pinning their predicates; this pins the machinery the Adapters used to inline
 * four times: the shrink-only diff, the baseline-load fallback, the write/read
 * round-trip over the {callers, note} shape, and the CLI-entrypoint guard.
 *
 * Pure pieces only — no git scan, no process.exit. (The full runSeamCheck arm
 * wiring is exercised end-to-end by the four per-Seam scripts in CI.)
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const {
  diffBaseline,
  loadBaseline,
  writeBaselineFile,
  isCliEntrypoint,
  REPO_ROOT,
} = await import("../scripts/ci/seam-check-lib.ts");

describe("seam-check-lib: diffBaseline (shrink-only ratchet)", () => {
  test("a current violation absent from the baseline is NEW (fail closed)", () => {
    const diff = diffBaseline(
      ["src/a.ts", "src/b.ts"],
      { callers: ["src/a.ts"], note: "" },
    );
    assert.deepEqual(diff.newViolations, ["src/b.ts"]);
    assert.deepEqual(diff.fixedCallers, []);
  });

  test("a baseline entry that no longer violates is a fixedCaller (stale baseline)", () => {
    const diff = diffBaseline(
      ["src/a.ts"],
      { callers: ["src/a.ts", "src/b.ts"], note: "" },
    );
    assert.deepEqual(diff.newViolations, []);
    assert.deepEqual(diff.fixedCallers, ["src/b.ts"]);
  });

  test("an exact-match baseline yields no new and no fixed (clean pass)", () => {
    const diff = diffBaseline(
      ["src/a.ts", "src/b.ts"],
      { callers: ["src/a.ts", "src/b.ts"], note: "" },
    );
    assert.deepEqual(diff.newViolations, []);
    assert.deepEqual(diff.fixedCallers, []);
  });

  test("a grown baseline AND a fix surface simultaneously (mixed drift)", () => {
    // current = {a, c}; baseline = {a, b}: c is new, b is fixed.
    const diff = diffBaseline(
      ["src/a.ts", "src/c.ts"],
      { callers: ["src/a.ts", "src/b.ts"], note: "" },
    );
    assert.deepEqual(diff.newViolations, ["src/c.ts"]);
    assert.deepEqual(diff.fixedCallers, ["src/b.ts"]);
  });

  test("an empty baseline makes every current violation new (unseeded)", () => {
    const diff = diffBaseline(
      ["src/a.ts"],
      { callers: [], note: "baseline not yet seeded" },
    );
    assert.deepEqual(diff.newViolations, ["src/a.ts"]);
    assert.deepEqual(diff.fixedCallers, []);
  });
});

describe("seam-check-lib: loadBaseline fallback", () => {
  test("a missing baseline file falls back to an empty unseeded baseline", async () => {
    const missing = join(REPO_ROOT, "scripts/ci/__does-not-exist__.json");
    const baseline = await loadBaseline(missing);
    assert.deepEqual(baseline.callers, []);
    assert.equal(baseline.note, "baseline not yet seeded");
  });
});

describe("seam-check-lib: writeBaselineFile / loadBaseline round-trip", () => {
  test("written baseline reloads with identical callers and a stamped note", async () => {
    const dir = await mkdtemp(join(tmpdir(), "seam-check-lib-"));
    try {
      const path = join(dir, "x-seam-baseline.json");
      const callers = ["src/a.ts", "src/b.ts"];
      await writeBaselineFile(path, callers, "x-seam-check", "X ratchet: shrink only.");

      const reloaded = await loadBaseline(path);
      assert.deepEqual(reloaded.callers, callers);
      assert.match(
        reloaded.note,
        /Auto-generated by scripts\/ci\/x-seam-check\.ts --write-baseline on .+\. X ratchet: shrink only\./,
      );

      // The on-disk form is pretty-printed JSON with a trailing newline,
      // matching the historic per-check writeBaselineFile output.
      const raw = await readFile(path, "utf8");
      assert.ok(raw.endsWith("\n"));
      assert.equal(raw, JSON.stringify(JSON.parse(raw), null, 2) + "\n");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe("seam-check-lib: isCliEntrypoint guard", () => {
  test("returns false when the module URL is not process.argv[1]", () => {
    // Under the test runner, argv[1] is the test entry, never an Adapter — so
    // importing an Adapter (e.g. for the predicate tests) does NOT trigger a
    // scan or a process.exit.
    assert.equal(
      isCliEntrypoint("file:///some/other/scripts/ci/redis-seam-check.ts"),
      false,
    );
  });
});
