/**
 * scripts/ci/hydra-target-wire-or-retire-emit.ts — Deterministic emitter for
 * the wire-or-retire half of `/hydra-target-cleanup` (step 4 of the Target
 * dead-code cleanup plan).
 *
 * The demote sweep (hydra-target-cleanup-emit.ts) handles the mechanical
 * findings; this emitter handles the JUDGMENT ones. Its input is the Target's
 * committed wiring-status ledger (docs/agents/wiring-status.md, generated by
 * `npm run deadcode:ledger` in hydra-betting): every module whose status is
 * `wire-or-retire` — past the 45-day wiring grace period with no runtime
 * importer — needs a deliberate decision: WIRE it (it was built with intent
 * that stalled) or RETIRE it (the intent is gone). That is an opinion, not a
 * green-test check, so — mirroring the orchestrator's confidence gate
 * (hydra-architecture-scan precedent) — items route to **`needs-triage`**
 * (the `triage` lane), NOT `ready-for-agent`. The item body carries the
 * decision protocol; hydra-target-sweep (or the operator via
 * /hydra-review's per-Target drain) advances it into one of three outcomes:
 *
 *   (a) WIRE   — intent recoverable: rewrite into a concrete ready-for-agent
 *                wiring task.
 *   (b) RETIRE — intent gone: rewrite into a ready-for-agent retirement task
 *                citing the deadcode scan (Target CLAUDE.md rule 3).
 *   (c) UNCLEAR — route to ready-for-human. Never delete on ambiguity.
 *
 * This emitter NEVER deletes anything and never asks an agent to delete
 * without the triage decision in between. Protected providers never appear
 * (the ledger already classifies them out of wire-or-retire).
 *
 * It reads the COMMITTED ledger rather than regenerating it — the skill must
 * not mutate the Target's working tree, and the ledger is refreshed by every
 * `deadcode:update-baseline` run on the Target side. Staleness is handled by
 * the item body's "verify first" step plus dedup against open items.
 *
 * The PURE core is {@link planWireOrRetireEmit}; only the thin CLI wrapper
 * touches fs and `gh` (GitHub Issues on the Target repo — ADR-0031). Same
 * shape as the demote emitter (scripts/ci/hydra-target-cleanup-emit.ts).
 *
 * Usage (invoked by the /hydra-target-cleanup playbook after the demote emit):
 *
 *   # dry-run: prints the plan, files nothing
 *   npx tsx scripts/ci/hydra-target-wire-or-retire-emit.ts
 *
 *   # apply: files one needs-triage decision item per module
 *   npx tsx scripts/ci/hydra-target-wire-or-retire-emit.ts --apply
 */

import { readFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";

/** Max decision items a single run files — judgment work must not flood triage. */
export const WIRE_OR_RETIRE_EMIT_CAP = 3;

/** Open wire-or-retire items above this → the run emits nothing. */
export const WIRE_OR_RETIRE_SATURATION_CAP = 5;

/** Label stamped on every emitted item — the saturation/dedup count seam. */
export const WIRE_OR_RETIRE_LABEL = "wire-or-retire";

export const TARGET_ROOT = "/home/gabe/hydra-betting";
export const LEDGER_FILE = `${TARGET_ROOT}/docs/agents/wiring-status.md`;

/** The Target repo whose GitHub-Issues board is the tracker (ADR-0031). */
export const TARGET_REPO = "gaberoo322/hydra-betting";

/** One parsed ledger row. */
export interface LedgerRow {
  /** Repo-relative module path as the ledger renders it (e.g. "web/src/lib/foo.ts"). */
  path: string;
  status: string;
  importedBy: string;
  lastTouched: string;
}

/**
 * Parse the wiring-status ledger markdown into rows. The table format is
 * canonical (rendered by hydra-betting's renderWiringLedger, pinned by its
 * tests), so a strict line parse is appropriate — a row that does not parse
 * is skipped, never guessed at.
 */
export function parseLedger(markdown: string): LedgerRow[] {
  const rows: LedgerRow[] = [];
  for (const line of markdown.split("\n")) {
    const m = line.match(/^\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|\s*$/);
    if (!m) continue;
    rows.push({
      path: m[1].trim(),
      status: m[2].trim(),
      importedBy: m[3].trim(),
      lastTouched: m[4].trim(),
    });
  }
  return rows;
}

/** Render the backlog item title. The path is the dedup identity. */
export function renderWireOrRetireTitle(path: string): string {
  if (!path.trim()) {
    throw new Error("renderWireOrRetireTitle: refusing to render an empty path");
  }
  return `cleanup(target): wire-or-retire ${path.trim()}`;
}

/** Recover the path identity from an open item title, or null. */
export function identityFromOpenItemTitle(title: string): string | null {
  const m = title.trim().match(/^cleanup\(target\): wire-or-retire\s+(\S+)$/);
  if (!m) return null;
  return m[1].trim() || null;
}

/**
 * Render the decision-item body. Title and body come from the same row in one
 * pass (the #1449/#1005 drift guard).
 */
function renderWireOrRetireBody(row: LedgerRow, isoDate: string): string {
  const lines: string[] = [];
  lines.push(`# cleanup(target): wire-or-retire \`${row.path}\``);
  lines.push("");
  lines.push(`> Surfaced by \`/hydra-target-cleanup\` on ${isoDate} from the Target's wiring-status ledger (\`docs/agents/wiring-status.md\`).`);
  lines.push("> This is a JUDGMENT item (needs-triage), not a mechanical one — do NOT delete anything while it sits in triage.");
  lines.push("");
  lines.push("## Finding");
  lines.push("");
  lines.push(
    `\`${row.path}\` is unreachable from every runtime entry point (imported by: ${row.importedBy}), and was last touched ${row.lastTouched} — past the 45-day wiring grace period. Hydra builds modules first and wires them later; this one's wiring never arrived. A deliberate decision is due: wire it or retire it.`,
  );
  lines.push("");
  lines.push("## Decision protocol (for the sweep agent or operator)");
  lines.push("");
  lines.push("1. **Verify first** (the ledger may be a regeneration behind): check the module still appears in the committed `docs/agents/wiring-status.md` on current `main` AND still has no production importer (`rg` its import path under `web/src`). Do not regenerate the ledger for this. If the module was wired or removed since the scan, close this item as stale.");
  lines.push("2. **Recover the intent**: `git log --follow` the module (who created it, in which cycle, alongside what); search `~/hydra` config/direction (vision, priorities, roadmap) and the backlog (open AND done lanes) for the feature it belongs to.");
  lines.push("3. **Decide** — exactly one of:");
  lines.push("   - **(a) WIRE** — the intent is live (matches a current priority or an obvious runtime seam exists): rewrite this item into a concrete wiring task (name the entry point / route / runner to wire into), label `ready-for-agent`, move to `queued`.");
  lines.push(`   - **(b) RETIRE** — the intent is gone (superseded, venue dropped, experiment concluded): rewrite this item into a retirement task — delete the module AND its test file, run \`npm run deadcode:update-baseline\` (refreshes baseline + ledger), commit citing this scan (module path, scan date ${isoDate}, Target CLAUDE.md rule 3) — label \`ready-for-agent\`, move to \`queued\`.`);
  lines.push("   - **(c) UNCLEAR** — intent cannot be established either way: label `ready-for-human`, move to `backlog`, and STOP. Ambiguity never resolves to deletion (CLAUDE.md rule 6, fail closed).");
  lines.push("");
  lines.push("## Files in scope");
  lines.push("");
  lines.push(`- \`${row.path}\``);
  lines.push("- `web/deadcode-baseline.json` + `docs/agents/wiring-status.md` (regenerated, retire path only)");
  lines.push("");
  lines.push("## Acceptance criteria (for the FOLLOW-UP task this item becomes)");
  lines.push("");
  lines.push("- [ ] Wire path: the module is imported from a runtime entry point; `npm test` + `npm run typecheck` pass; the ledger no longer lists it.");
  lines.push("- [ ] Retire path: module + its tests deleted with the scan citation; `npm test` + `npm run typecheck` + `npm run deadcode:check` pass with a tightened, committed baseline + regenerated ledger.");
  lines.push("- [ ] Either way: no other module is touched.");
  lines.push("");
  lines.push("---");
  lines.push("*Generated by hydra-target-cleanup (wire-or-retire phase, step 4 of the Target dead-code cleanup plan). Routes to `needs-triage` because wire-vs-retire is a judgment call, not a green-test check.*");
  return lines.join("\n").trimEnd() + "\n";
}

export interface PlannedWireOrRetireItem {
  row: LedgerRow;
  title: string;
  body: string;
}

export interface WireOrRetireEmitPlan {
  items: PlannedWireOrRetireItem[];
  dropped: Array<{ row: LedgerRow; reason: string }>;
  /** Count of wire-or-retire rows in the ledger (pre-filter). */
  eligibleCount: number;
}

/**
 * The PURE planner: parse → keep wire-or-retire rows → dedup vs open items →
 * cap → render. Oldest modules first (they have waited longest).
 */
export function planWireOrRetireEmit(
  ledgerMarkdown: string,
  openItemTitles: string[],
  isoDate: string,
  cap: number = WIRE_OR_RETIRE_EMIT_CAP,
): WireOrRetireEmitPlan {
  const rows = parseLedger(ledgerMarkdown).filter((r) => r.status === "wire-or-retire");
  const dropped: Array<{ row: LedgerRow; reason: string }> = [];

  const openPaths = new Set<string>();
  for (const title of openItemTitles) {
    const id = identityFromOpenItemTitle(title);
    if (id) openPaths.add(id);
  }

  const fresh: LedgerRow[] = [];
  const seen = new Set<string>();
  for (const row of rows) {
    if (!row.path) continue;
    if (openPaths.has(row.path) || seen.has(row.path)) {
      dropped.push({ row, reason: "an open wire-or-retire item already covers this module" });
      continue;
    }
    seen.add(row.path);
    fresh.push(row);
  }

  // Oldest last-touched first; "unknown" sorts last (verify-first handles it).
  fresh.sort((a, b) => {
    const ak = a.lastTouched === "unknown" ? "9999" : a.lastTouched;
    const bk = b.lastTouched === "unknown" ? "9999" : b.lastTouched;
    return ak.localeCompare(bk) || a.path.localeCompare(b.path);
  });

  const toEmit = fresh.slice(0, cap);
  for (const row of fresh.slice(cap)) {
    dropped.push({ row, reason: `over the per-run cap of ${cap}` });
  }

  const items: PlannedWireOrRetireItem[] = toEmit.map((row) => ({
    row,
    title: renderWireOrRetireTitle(row.path),
    body: renderWireOrRetireBody(row, isoDate),
  }));

  return { items, dropped, eligibleCount: rows.length };
}

// ---------------------------------------------------------------------------
// Thin CLI wrapper (the only part that touches fs / gh).
// ---------------------------------------------------------------------------
// ADR-0031: the Target's tracker is the GitHub-Issues board on
// gaberoo322/hydra-betting, NOT the retired `/api/backlog` Redis surface
// (deleted by #3439 / PR #3455 — it now returns 404). Items are filed via
// `gh issue create --label needs-triage --label wire-or-retire` and
// deduped/saturation-checked via `gh issue list --label wire-or-retire` — the
// exact shape the already-migrated demote sibling
// (scripts/ci/hydra-target-cleanup-emit.ts) uses. This is the fix for the
// class being permanently inert: the old HTTP call to the retired /api/backlog
// surface threw on the first call (404), main() caught it into process.exit(1),
// and the runner never reached its file step at all — with or without the
// labels present.

interface IssueTitle {
  title?: string;
}

/**
 * Read the titles of every OPEN GitHub Issue on the Target repo carrying the
 * wire-or-retire label (the dedup + saturation input). Throws on a `gh`
 * failure so the caller can fail closed. `--state open` (the `gh` default for
 * `issue list`) is the "not done" filter — a closed issue is the `done`
 * transition under ADR-0031.
 */
function readOpenWireOrRetireItemTitles(): string[] {
  try {
    const out = execFileSync(
      "gh",
      [
        "issue",
        "list",
        "--repo",
        TARGET_REPO,
        "--label",
        WIRE_OR_RETIRE_LABEL,
        "--json",
        "title",
      ],
      { encoding: "utf-8" },
    );
    const issues = JSON.parse(out) as IssueTitle[];
    return issues.map((i) => i.title ?? "").filter(Boolean);
  } catch (err) {
    throw new Error(
      `gh issue list --label ${WIRE_OR_RETIRE_LABEL} failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * File one decision item on the Target repo carrying BOTH `wire-or-retire`
 * AND `needs-triage`. Co-presence is the invariant: collect-state.sh counts a
 * wire-or-retire item only when BOTH labels are present, so filing either
 * label alone leaves the `wire_or_retire_target` signal dark (issue #3720).
 */
function createTriageIssue(title: string, body: string): string {
  try {
    const out = execFileSync(
      "gh",
      [
        "issue",
        "create",
        "--repo",
        TARGET_REPO,
        "--title",
        title,
        "--body",
        body,
        "--label",
        WIRE_OR_RETIRE_LABEL,
        "--label",
        "needs-triage",
      ],
      { encoding: "utf-8" },
    );
    // gh issue create prints the issue URL on success.
    const urlMatch = out.trim().match(/github\.com\/.*\/issues\/(\d+)/);
    const issueNum = urlMatch?.[1] ?? "?";
    return `filed as #${issueNum} → needs-triage`;
  } catch (err) {
    throw new Error(
      `gh issue create failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

function main(argv: string[]): void {
  const args = argv.slice(2);
  const apply = args.includes("--apply");
  const ledgerPath = args.find((a) => !a.startsWith("--")) ?? LEDGER_FILE;

  if (!existsSync(ledgerPath)) {
    console.error(
      `hydra-target-wire-or-retire-emit: ledger not found at ${ledgerPath}. The Target generates it via \`npm run deadcode:ledger\` (hydra-betting PR #98).`,
    );
    process.exit(1);
  }
  const ledgerMarkdown = readFileSync(ledgerPath, "utf-8");

  // Dedup + saturation read. A failed read MUST NOT hard-abort the run into a
  // process.exit(1) that reads as "filed nothing because nothing was eligible"
  // (the old /api/backlog-404 failure mode that hid this bug for weeks). It
  // fails CLOSED — emit nothing, because filing without dedup risks
  // duplicates — but reports the degradation on stdout as a distinguishable
  // reason first, never as the silence that reads as "nothing was eligible".
  let openTitles: string[];
  try {
    openTitles = readOpenWireOrRetireItemTitles();
  } catch (err) {
    console.log(
      `hydra-target-wire-or-retire-emit: DEGRADED — could not read open wire-or-retire issues for dedup/saturation (${err instanceof Error ? err.message : String(err)}); emitting nothing this run (fail closed — filing without dedup would risk duplicates).`,
    );
    return;
  }

  if (openTitles.length > WIRE_OR_RETIRE_SATURATION_CAP) {
    console.log(
      `hydra-target-wire-or-retire-emit: board saturated (${openTitles.length} open wire-or-retire items > ${WIRE_OR_RETIRE_SATURATION_CAP} cap) — emitting nothing.`,
    );
    return;
  }

  const isoDate = new Date().toISOString().slice(0, 10);
  const plan = planWireOrRetireEmit(ledgerMarkdown, openTitles, isoDate);

  console.log(
    `hydra-target-wire-or-retire-emit — Target ledger — ${new Date().toISOString()} — ${apply ? "apply" : "dry-run"}`,
  );
  console.log("");
  console.log(`wire-or-retire rows in ledger: ${plan.eligibleCount}`);
  console.log(`to emit:                       ${plan.items.length} (cap ${WIRE_OR_RETIRE_EMIT_CAP})`);
  console.log(`dropped:                       ${plan.dropped.length}`);
  console.log("");

  for (const item of plan.items) {
    console.log(`• ${item.title}  [last touched ${item.row.lastTouched}]`);
    if (!apply) {
      console.log("  --- body ---");
      console.log(item.body.replace(/^/gm, "  "));
      console.log("");
    } else {
      try {
        const outcome = createTriageIssue(item.title, item.body);
        console.log(`  ✓ ${outcome}`);
      } catch (err) {
        console.error(
          `  ✗ filing failed: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }
  }

  const reasons = new Map<string, number>();
  for (const d of plan.dropped) reasons.set(d.reason, (reasons.get(d.reason) ?? 0) + 1);
  for (const [reason, count] of reasons) console.log(`dropped ${count}: ${reason}`);

  if (!apply) {
    console.log("");
    console.log("(dry-run; no issues created — pass --apply to file them on GitHub)");
  }
}

// Only run when executed directly (not when imported by the test).
if (import.meta.url === `file://${process.argv[1]}`) {
  main(process.argv);
}
