/**
 * scripts/ci/hydra-target-wire-or-retire-emit.ts — Deterministic emitter for
 * the wire-or-retire half of `/hydra-target-cleanup` (step 4 of the Target
 * dead-code cleanup plan).
 *
 * The demote sweep (hydra-target-cleanup-emit.ts) handles the mechanical
 * findings; this emitter handles the JUDGMENT ones. Its input is the Target's
 * committed wiring-status ledger (docs/agents/wiring-status.md, generated by
 * the Target's `npm run deadcode:ledger` script): every module whose status is
 * `wire-or-retire` — past the 45-day wiring grace period with no runtime
 * importer — needs a deliberate decision: WIRE it (it was built with intent
 * that stalled) or RETIRE it (the intent is gone). That is an opinion, not a
 * green-test check, so — mirroring the orchestrator's confidence gate
 * (hydra-architecture-scan precedent) — items route to **`needs-triage`**
 * (the `triage` lane), NOT `ready-for-agent`. The item body carries the
 * decision protocol; hydra-target-sweep (or the operator via
 * /hydra-review's per-Target drain) advances it into one of three outcomes:
 *
 *   (a) WIRE   — intent recoverable: rewrite into a concrete ready-for-agent
 *                wiring task.
 *   (b) RETIRE — intent gone: rewrite into a ready-for-agent retirement task
 *                citing the deadcode scan (Target CLAUDE.md rule 3).
 *   (c) UNCLEAR — route to ready-for-human. Never delete on ambiguity.
 *
 * This emitter NEVER deletes anything and never asks an agent to delete
 * without the triage decision in between. Protected providers never appear
 * (the ledger already classifies them out of wire-or-retire).
 *
 * It reads the COMMITTED ledger rather than regenerating it — the skill must
 * not mutate the Target's working tree, and the ledger is refreshed by every
 * `deadcode:update-baseline` run on the Target side. Staleness is handled by
 * the item body's "verify first" step plus dedup against open items.
 *
 * The PURE core is {@link planWireOrRetireEmit}; only the thin CLI wrapper
 * touches fs and `gh` — the SAME shape as its already-migrated sibling
 * {@link ./hydra-target-cleanup-emit.ts}. Findings sink: GitHub Issues on
 * the Target's repo (ADR-0031) via `gh issue create`/`gh issue list`
 * — NOT the retired `/api/backlog` surface (issue #3720: this runner's first
 * call used to `fetch()` that 404'd endpoint, so it never reached its file
 * step, with or without the right labels).
 *
 * Usage (invoked by the /hydra-target-cleanup playbook after the demote emit):
 *
 *   # dry-run: prints the plan, files nothing
 *   npx tsx scripts/ci/hydra-target-wire-or-retire-emit.ts
 *
 *   # apply: files one needs-triage + wire-or-retire decision item per module
 *   npx tsx scripts/ci/hydra-target-wire-or-retire-emit.ts --apply
 *
 * Target resolution (issue #4553): the ledger path
 * (`<workspace>/docs/agents/wiring-status.md`) and the Target repo are resolved
 * LAZILY at CLI time through {@link collectTargetFacts} — which composes
 * src/target-config.ts, the one owner of Target defaults (ADR-0002) — never
 * hardcoded and never at module load. A Target that ships no ledger generator
 * (no `deadcode:ledger` script) and has no ledger is a clean skip (exit 0),
 * mirroring the hydra-target-build preflight guard (#4531).
 */

import { existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { collectTargetFacts } from "../target/print-target-facts.ts";
import {
  runEmitShell,
  tallyDropReasons,
  type EmitShellSpec,
  type EmitSourceResult,
} from "./hydra-emit-shell.ts";

/** Max decision items a single run files — judgment work must not flood triage. */
export const WIRE_OR_RETIRE_EMIT_CAP = 3;

/** Open wire-or-retire items above this → the run emits nothing. */
export const WIRE_OR_RETIRE_SATURATION_CAP = 5;

/** Label stamped on every emitted item — the saturation/dedup count seam. */
export const WIRE_OR_RETIRE_LABEL = "wire-or-retire";

/**
 * Co-presence label — every emitted item ALWAYS carries this alongside
 * {@link WIRE_OR_RETIRE_LABEL} (never one without the other). collect-state.sh
 * counts an item only when BOTH are present (the #2721 lane guard), so filing
 * either alone would leave `wire_or_retire_target_available` false.
 */
export const WIRE_OR_RETIRE_TRIAGE_LABEL = "needs-triage";

/** Fixed convention path of the wiring-status ledger, relative to the Target workspace. */
export const LEDGER_RELATIVE_PATH = "docs/agents/wiring-status.md";

/** The Target-side package.json script that generates the ledger. */
export const LEDGER_GENERATOR_SCRIPT = "deadcode:ledger";

/** One parsed ledger row. */
export interface LedgerRow {
  /** Repo-relative module path as the ledger renders it (e.g. "web/src/lib/foo.ts"). */
  path: string;
  status: string;
  importedBy: string;
  lastTouched: string;
}

/**
 * Parse the wiring-status ledger markdown into rows. The table format is
 * canonical (rendered by hydra-betting's renderWiringLedger, pinned by its
 * tests), so a strict line parse is appropriate — a row that does not parse
 * is skipped, never guessed at.
 */
export function parseLedger(markdown: string): LedgerRow[] {
  const rows: LedgerRow[] = [];
  for (const line of markdown.split("\n")) {
    const m = line.match(/^\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|\s*$/);
    if (!m) continue;
    rows.push({
      path: m[1].trim(),
      status: m[2].trim(),
      importedBy: m[3].trim(),
      lastTouched: m[4].trim(),
    });
  }
  return rows;
}

/** Render the backlog item title. The path is the dedup identity. */
export function renderWireOrRetireTitle(path: string): string {
  if (!path.trim()) {
    throw new Error("renderWireOrRetireTitle: refusing to render an empty path");
  }
  return `cleanup(target): wire-or-retire ${path.trim()}`;
}

/** Recover the path identity from an open item title, or null. */
export function identityFromOpenItemTitle(title: string): string | null {
  const m = title.trim().match(/^cleanup\(target\): wire-or-retire\s+(\S+)$/);
  if (!m) return null;
  return m[1].trim() || null;
}

/**
 * Render the decision-item body. Title and body come from the same row in one
 * pass (the #1449/#1005 drift guard).
 */
function renderWireOrRetireBody(row: LedgerRow, isoDate: string): string {
  const lines: string[] = [];
  lines.push(`# cleanup(target): wire-or-retire \`${row.path}\``);
  lines.push("");
  lines.push(`> Surfaced by \`/hydra-target-cleanup\` on ${isoDate} from the Target's wiring-status ledger (\`docs/agents/wiring-status.md\`).`);
  lines.push("> This is a JUDGMENT item (needs-triage), not a mechanical one — do NOT delete anything while it sits in triage.");
  lines.push("");
  lines.push("## Finding");
  lines.push("");
  lines.push(
    `\`${row.path}\` is unreachable from every runtime entry point (imported by: ${row.importedBy}), and was last touched ${row.lastTouched} — past the 45-day wiring grace period. Hydra builds modules first and wires them later; this one's wiring never arrived. A deliberate decision is due: wire it or retire it.`,
  );
  lines.push("");
  lines.push("## Decision protocol (for the sweep agent or operator)");
  lines.push("");
  lines.push("1. **Verify first** (the ledger may be a regeneration behind): check the module still appears in the committed `docs/agents/wiring-status.md` on current `main` AND still has no production importer (`rg` its import path under `web/src`). Do not regenerate the ledger for this. If the module was wired or removed since the scan, close this item as stale.");
  lines.push("2. **Recover the intent**: `git log --follow` the module (who created it, in which cycle, alongside what); search `~/hydra` config/direction (vision, priorities, roadmap) and the backlog (open AND done lanes) for the feature it belongs to.");
  lines.push("3. **Decide** — exactly one of:");
  lines.push("   - **(a) WIRE** — the intent is live (matches a current priority or an obvious runtime seam exists): rewrite this item into a concrete wiring task (name the entry point / route / runner to wire into), label `ready-for-agent`, move to `queued`.");
  lines.push(`   - **(b) RETIRE** — the intent is gone (superseded, venue dropped, experiment concluded): rewrite this item into a retirement task — delete the module AND its test file, run \`npm run deadcode:update-baseline\` (refreshes baseline + ledger), commit citing this scan (module path, scan date ${isoDate}, Target CLAUDE.md rule 3) — label \`ready-for-agent\`, move to \`queued\`.`);
  lines.push("   - **(c) UNCLEAR** — intent cannot be established either way: label `ready-for-human`, move to `backlog`, and STOP. Ambiguity never resolves to deletion (CLAUDE.md rule 6, fail closed).");
  lines.push("");
  lines.push("## Files in scope");
  lines.push("");
  lines.push(`- \`${row.path}\``);
  lines.push("- `web/deadcode-baseline.json` + `docs/agents/wiring-status.md` (regenerated, retire path only)");
  lines.push("");
  lines.push("## Acceptance criteria (for the FOLLOW-UP task this item becomes)");
  lines.push("");
  lines.push("- [ ] Wire path: the module is imported from a runtime entry point; `npm test` + `npm run typecheck` pass; the ledger no longer lists it.");
  lines.push("- [ ] Retire path: module + its tests deleted with the scan citation; `npm test` + `npm run typecheck` + `npm run deadcode:check` pass with a tightened, committed baseline + regenerated ledger.");
  lines.push("- [ ] Either way: no other module is touched.");
  lines.push("");
  lines.push("---");
  lines.push("*Generated by hydra-target-cleanup (wire-or-retire phase, step 4 of the Target dead-code cleanup plan). Routes to `needs-triage` because wire-vs-retire is a judgment call, not a green-test check.*");
  return lines.join("\n").trimEnd() + "\n";
}

export interface PlannedWireOrRetireItem {
  row: LedgerRow;
  title: string;
  body: string;
}

export interface WireOrRetireEmitPlan {
  items: PlannedWireOrRetireItem[];
  dropped: Array<{ row: LedgerRow; reason: string }>;
  /** Count of wire-or-retire rows in the ledger (pre-filter). */
  eligibleCount: number;
}

/**
 * The PURE planner: parse → keep wire-or-retire rows → dedup vs open items →
 * cap → render. Oldest modules first (they have waited longest).
 */
export function planWireOrRetireEmit(
  ledgerMarkdown: string,
  openItemTitles: string[],
  isoDate: string,
  cap: number = WIRE_OR_RETIRE_EMIT_CAP,
): WireOrRetireEmitPlan {
  const rows = parseLedger(ledgerMarkdown).filter((r) => r.status === "wire-or-retire");
  const dropped: Array<{ row: LedgerRow; reason: string }> = [];

  const openPaths = new Set<string>();
  for (const title of openItemTitles) {
    const id = identityFromOpenItemTitle(title);
    if (id) openPaths.add(id);
  }

  const fresh: LedgerRow[] = [];
  const seen = new Set<string>();
  for (const row of rows) {
    if (!row.path) continue;
    if (openPaths.has(row.path) || seen.has(row.path)) {
      dropped.push({ row, reason: "an open wire-or-retire item already covers this module" });
      continue;
    }
    seen.add(row.path);
    fresh.push(row);
  }

  // Oldest last-touched first; "unknown" sorts last (verify-first handles it).
  fresh.sort((a, b) => {
    const ak = a.lastTouched === "unknown" ? "9999" : a.lastTouched;
    const bk = b.lastTouched === "unknown" ? "9999" : b.lastTouched;
    return ak.localeCompare(bk) || a.path.localeCompare(b.path);
  });

  const toEmit = fresh.slice(0, cap);
  for (const row of fresh.slice(cap)) {
    dropped.push({ row, reason: `over the per-run cap of ${cap}` });
  }

  const items: PlannedWireOrRetireItem[] = toEmit.map((row) => ({
    row,
    title: renderWireOrRetireTitle(row.path),
    body: renderWireOrRetireBody(row, isoDate),
  }));

  return { items, dropped, eligibleCount: rows.length };
}

// ---------------------------------------------------------------------------
// Thin CLI wrapper (the only part that touches fs / git / gh) — same shape
// as the already-migrated sibling hydra-target-cleanup-emit.ts.
// ---------------------------------------------------------------------------

interface IssueTitle {
  title?: string;
}

/**
 * Read every OPEN GitHub Issue on the Target repo carrying the
 * `wire-or-retire` label (used for dedup and the saturation check). Aborts
 * (throws) if the board can't be read — emitting without dedup/saturation
 * inputs is exactly how a flood happens (fail closed).
 */
function readOpenWireOrRetireItemTitles(targetRepo: string): string[] {
  try {
    const out = execFileSync(
      "gh",
      [
        "issue",
        "list",
        "--repo",
        targetRepo,
        "--label",
        WIRE_OR_RETIRE_LABEL,
        "--json",
        "title",
      ],
      { encoding: "utf-8" },
    );
    const issues = JSON.parse(out) as IssueTitle[];
    return issues.map((i) => i.title ?? "").filter(Boolean);
  } catch (err) {
    throw new Error(
      `gh issue list --label ${WIRE_OR_RETIRE_LABEL} failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * File one decision item via GitHub Issues on the Target repo. Stamps BOTH
 * {@link WIRE_OR_RETIRE_TRIAGE_LABEL} and {@link WIRE_OR_RETIRE_LABEL} in the
 * SAME `gh issue create` call — the co-presence invariant collect-state.sh
 * keys its count on (#3720).
 */
function createTriageItem(targetRepo: string, title: string, body: string): string {
  try {
    const out = execFileSync(
      "gh",
      [
        "issue",
        "create",
        "--repo",
        targetRepo,
        "--title",
        title,
        "--body",
        body,
        "--label",
        WIRE_OR_RETIRE_TRIAGE_LABEL,
        "--label",
        WIRE_OR_RETIRE_LABEL,
      ],
      { encoding: "utf-8" },
    );
    // gh issue create prints the issue URL on success.
    const urlMatch = out.trim().match(/github\.com\/.*\/issues\/(\d+)/);
    const issueNum = urlMatch?.[1] ?? "?";
    return `filed as #${issueNum}`;
  } catch (err) {
    throw new Error(
      `gh issue create failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Load the ledger markdown (issue #4393). The read is guarded now — the
 * former main() read the file unguarded, so an unreadable ledger crashed with
 * a raw stack trace; the result shape makes the shell fail loud with a
 * one-line diagnostic instead.
 */
function loadLedger(path: string): EmitSourceResult<string> {
  try {
    return { ok: true, source: readFileSync(path, "utf-8") };
  } catch (err) {
    return {
      ok: false,
      error: `failed to read ledger at ${path}: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/** The resolved Target inputs the CLI spec factory needs (issue #4553). */
export interface WireOrRetireTargetInputs {
  /** Absolute path of the Target's wiring-status ledger. */
  ledgerPath: string;
  /** `owner/name` of the Target's GitHub repo — used by BOTH gh calls. */
  targetRepo: string;
}

/** Join the Target workspace onto the fixed ledger convention path. */
export function ledgerPathForWorkspace(workspace: string): string {
  return `${workspace.replace(/\/+$/, "")}/${LEDGER_RELATIVE_PATH}`;
}

/**
 * Resolve the Target inputs through {@link collectTargetFacts} (the
 * target-config seam, ADR-0002). Called ONLY from the CLI wrapper, never at
 * module load, so importing this module emits no target-config fallback
 * warnings.
 */
export function resolveWireOrRetireTargetInputs(): WireOrRetireTargetInputs & { appPackageJsonPath: string } {
  const facts = collectTargetFacts();
  const ws = facts.workspace.replace(/\/+$/, "");
  // Manifest failure (appSubdir unknown) → probe only <workspace>/package.json
  // (positive-evidence-only, same as the preflight guard).
  const appSubdir = facts.manifest.ok ? facts.manifest.appSubdir.replace(/\/+$/, "") : "";
  return {
    ledgerPath: ledgerPathForWorkspace(ws),
    targetRepo: facts.githubRepo,
    appPackageJsonPath: appSubdir ? `${ws}/${appSubdir}/package.json` : `${ws}/package.json`,
  };
}

/** Outcome of the ledgerless-Target pre-check (issue #4553, mirrors #4531). */
export type LedgerSkipDecision =
  | { skip: false }
  | { skip: true; message: string };

/**
 * PURE decision: should this run skip cleanly because the Target has no
 * ledger AND declares no generator?
 *
 *  - explicit positional source path → never skip (the operator asked for it;
 *    the shell's fail-loud missing-source path handles an absent file);
 *  - ledger present → never skip;
 *  - ledger absent + generator declared (positive evidence) → never skip, so
 *    the shell keeps today's fail-loud missing-source behaviour;
 *  - ledger absent + no generator (no/malformed package.json, no script) →
 *    skip with one informational line.
 *
 * `appPackageJsonText` is the raw package.json text, or `null` if unreadable.
 */
export function decideLedgerSkip(input: {
  explicitSourcePath: boolean;
  ledgerExists: boolean;
  ledgerPath: string;
  appPackageJsonText: string | null;
}): LedgerSkipDecision {
  if (input.explicitSourcePath || input.ledgerExists) return { skip: false };
  if (declaresLedgerGenerator(input.appPackageJsonText)) return { skip: false };
  return {
    skip: true,
    message:
      `Target declares no wiring ledger (no ${LEDGER_GENERATOR_SCRIPT} script; ledger absent at ${input.ledgerPath}) — wire-or-retire emit skipped, nothing filed.`,
  };
}

/** Positive evidence only: a parseable package.json with a non-empty generator script. */
function declaresLedgerGenerator(packageJsonText: string | null): boolean {
  if (packageJsonText === null) return false;
  try {
    const pkg = JSON.parse(packageJsonText) as { scripts?: Record<string, unknown> };
    const script = pkg?.scripts?.[LEDGER_GENERATOR_SCRIPT];
    return typeof script === "string" && script.trim().length > 0;
  } catch {
    /* intentional: a malformed package.json is not positive evidence of a generator */
    return false;
  }
}

/**
 * The CLI shell spec factory (issue #4393; parameterised by #4553): every
 * domain-specific piece of the former main() — the argv/guard/saturation/
 * print/apply loop (including the #3720 continue-on-filing-failure policy)
 * lives in the shared emit shell. Both gh calls receive the SAME resolved
 * `targetRepo`.
 */
export function buildWireOrRetireShellSpec(
  inputs: WireOrRetireTargetInputs,
): EmitShellSpec<string, string, PlannedWireOrRetireItem> {
  const { ledgerPath, targetRepo } = inputs;
  return {
    name: "hydra-target-wire-or-retire-emit",
    banner: "Target ledger",
    openItemNoun: "wire-or-retire items",
    saturationCap: WIRE_OR_RETIRE_SATURATION_CAP,
    defaultSourcePath: ledgerPath,
    missingSourceMessage: (path) =>
      `ledger not found at ${path}. The Target declares a ledger generator, so it is expected — regenerate it via the Target's \`npm run ${LEDGER_GENERATOR_SCRIPT}\` convention.`,
    loadSource: loadLedger,
    readOpenItems: () => readOpenWireOrRetireItemTitles(targetRepo),
    buildPlan: (ledgerMarkdown, openTitles, isoDate) => {
      const plan = planWireOrRetireEmit(ledgerMarkdown, openTitles, isoDate);
      return {
        items: plan.items,
        summaryLines: [
          `wire-or-retire rows in ledger: ${plan.eligibleCount}`,
          `to emit:                       ${plan.items.length} (cap ${WIRE_OR_RETIRE_EMIT_CAP})`,
          `dropped:                       ${plan.dropped.length}`,
        ],
        footerLines: tallyDropReasons(plan.dropped),
      };
    },
    itemLine: (item) => `• ${item.title}  [last touched ${item.row.lastTouched}]`,
    createItem: (item) => createTriageItem(targetRepo, item.title, item.body),
  };
}

function readTextOrNull(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    /* intentional: an absent/unreadable package.json means "no positive evidence" */
    return null;
  }
}

/** CLI entry: resolve the Target, run the ledgerless pre-check, then the shell. */
function main(argv: string[]): number {
  const resolved = resolveWireOrRetireTargetInputs();
  const explicitSourcePath = argv.slice(2).some((a) => !a.startsWith("--"));
  const decision = decideLedgerSkip({
    explicitSourcePath,
    ledgerExists: existsSync(resolved.ledgerPath),
    ledgerPath: resolved.ledgerPath,
    appPackageJsonText: explicitSourcePath ? null : readTextOrNull(resolved.appPackageJsonPath),
  });
  if (decision.skip) {
    console.log(`hydra-target-wire-or-retire-emit: ${decision.message}`);
    return 0;
  }
  return runEmitShell(buildWireOrRetireShellSpec(resolved), argv);
}

// Only run when executed directly (not when imported by the test).
if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = main(process.argv);
}
