#!/usr/bin/env -S npx tsx
/**
 * Redis Seam check — ADR-0009 closure ratchet.
 *
 * Forbids new imports of the legacy Redis surface (`redis-keys`,
 * `redis-adapter`) and the internal seam primitives (`redis/keys`,
 * `redis/kv`) from anywhere outside `src/redis/` itself.
 *
 * Implements a baseline ratchet: existing violations live in
 * `scripts/ci/redis-seam-baseline.json` and are tolerated. New
 * violations fail the gate. The baseline is allowed to *shrink* but
 * not grow — any caller that gets cleaned up must be removed from the
 * baseline, and a future caller that re-introduces the same import is
 * caught on its own merits.
 *
 * Usage:
 *   node --no-warnings --experimental-strip-types scripts/ci/redis-seam-check.ts
 *   npm run redis-seam-check
 *
 * Update flow when intentionally migrating a caller:
 *   1. Remove the legacy import.
 *   2. Run with `--write-baseline` to regenerate the baseline file.
 *   3. Commit the smaller baseline alongside the migration.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const FORBIDDEN_PATTERNS = [
  /from\s+['"][^'"]*\/redis-keys(?:\.ts)?['"]/,
  /from\s+['"][^'"]*\/redis-adapter(?:\.ts)?['"]/,
  /from\s+['"][^'"]*\/redis\/keys(?:\.ts)?['"]/,
  /from\s+['"][^'"]*\/redis\/kv(?:\.ts)?['"]/,
];

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), "../../..");
const SRC_DIR = join(REPO_ROOT, "src");
const REDIS_DIR = join(SRC_DIR, "redis");
const BASELINE_PATH = join(REPO_ROOT, "scripts/ci/redis-seam-baseline.json");
const WRITE_BASELINE = process.argv.includes("--write-baseline");

interface BaselineFile {
  /** Sorted list of `src/...` paths whose legacy imports are tolerated. */
  callers: string[];
  /** Free-form note explaining when this baseline was last regenerated. */
  note: string;
}

async function listTrackedSrcFiles(): Promise<string[]> {
  // git ls-files is faster and respects .gitignore.
  const { stdout } = await execFileAsync(
    "git",
    ["ls-files", "src/*.ts", "src/**/*.ts"],
    { cwd: REPO_ROOT },
  );
  return stdout
    .split("\n")
    .map(s => s.trim())
    .filter(Boolean);
}

function isInsideRedisDir(absolutePath: string): boolean {
  return absolutePath === REDIS_DIR || absolutePath.startsWith(REDIS_DIR + "/");
}

async function findViolations(): Promise<string[]> {
  const tracked = await listTrackedSrcFiles();
  const violations: string[] = [];
  for (const relPath of tracked) {
    const abs = join(REPO_ROOT, relPath);
    if (isInsideRedisDir(abs)) continue;
    let body: string;
    try {
      body = await readFile(abs, "utf8");
    } catch {
      continue;
    }
    for (const re of FORBIDDEN_PATTERNS) {
      if (re.test(body)) {
        violations.push(relPath);
        break;
      }
    }
  }
  return violations.sort();
}

async function loadBaseline(): Promise<BaselineFile> {
  try {
    const raw = await readFile(BASELINE_PATH, "utf8");
    return JSON.parse(raw) as BaselineFile;
  } catch {
    return { callers: [], note: "baseline not yet seeded" };
  }
}

async function writeBaselineFile(callers: string[]): Promise<void> {
  const payload: BaselineFile = {
    callers,
    note: `Auto-generated by scripts/ci/redis-seam-check.ts --write-baseline on ${new Date().toISOString()}. ADR-0009 closure ratchet: shrink only.`,
  };
  await writeFile(BASELINE_PATH, JSON.stringify(payload, null, 2) + "\n", "utf8");
}

async function main(): Promise<number> {
  const violations = await findViolations();

  if (WRITE_BASELINE) {
    await writeBaselineFile(violations);
    console.log(`[redis-seam-check] Wrote baseline with ${violations.length} entries to ${relative(REPO_ROOT, BASELINE_PATH)}`);
    return 0;
  }

  const baseline = await loadBaseline();
  const baselineSet = new Set(baseline.callers);
  const violationSet = new Set(violations);

  const newViolations = violations.filter(v => !baselineSet.has(v));
  const fixedCallers = baseline.callers.filter(c => !violationSet.has(c));

  if (newViolations.length > 0) {
    console.error("[redis-seam-check] NEW Redis-seam violations (ADR-0009):");
    for (const v of newViolations) console.error(`  - ${v}`);
    console.error("");
    console.error("These files import from redis-keys / redis-adapter / redis/keys / redis/kv.");
    console.error("Move the access behind a typed accessor in src/redis/<domain>.ts.");
    return 1;
  }

  if (fixedCallers.length > 0) {
    console.error("[redis-seam-check] Baseline is stale — these files no longer violate:");
    for (const c of fixedCallers) console.error(`  - ${c}`);
    console.error("");
    console.error("Re-run with --write-baseline and commit the shrunk baseline.");
    return 1;
  }

  console.log(`[redis-seam-check] OK — ${violations.length} known violations, no new ones.`);
  return 0;
}

main().then(
  code => process.exit(code),
  err => {
    console.error("[redis-seam-check] crash:", err);
    process.exit(2);
  },
);
