#!/usr/bin/env -S npx tsx
/**
 * Test-typecheck ratchet — issue #750 closure.
 *
 * `tsconfig.json` excludes `test/`, so `npm run typecheck` (`tsc --noEmit`)
 * never type-checks the test suite. `npm test` runs under tsx (transpile-only,
 * types erased), so test type errors are caught by NEITHER gate — they only
 * surface in an editor/LSP, and type rot accumulates silently.
 *
 * This check type-checks `test/**` (via `tsconfig.test.json`) and enforces a
 * shrink-only baseline: the current error COUNT lives in
 * `scripts/ci/test-typecheck-baseline.json` and is tolerated. The gate fails
 * only if the count *rises*. When the count drops, the gate also fails with a
 * "baseline is stale" message so the smaller number gets committed — the same
 * mechanic as `scripts/ci/redis-seam-check.ts` (ADR-0009 closure ratchet).
 *
 * It lives in its own sibling CI workflow (`.github/workflows/test-typecheck.yml`),
 * deliberately NOT inside `ci.yml`, because `ci.yml` is part of the Untouchable
 * Core (ADR-0001 / Tier-0, operator-only). A new non-blocking verification is a
 * normal (non-Tier-0) change, so it belongs in a separate workflow file — the
 * same pattern as `.github/workflows/secret-scan.yml`.
 *
 * Usage:
 *   npx tsx scripts/ci/test-typecheck-check.ts
 *   npm run typecheck:test            # human-facing: print the errors
 *
 * Update flow when intentionally fixing test type errors:
 *   1. Fix the errors.
 *   2. Run with `--write-baseline` to record the smaller count.
 *   3. Commit the shrunk baseline alongside the fix.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), "../../..");
const TSCONFIG = join(REPO_ROOT, "tsconfig.test.json");
const BASELINE_PATH = join(REPO_ROOT, "scripts/ci/test-typecheck-baseline.json");
const WRITE_BASELINE = process.argv.includes("--write-baseline");

interface BaselineFile {
  /** Number of `tsc` errors in `test/**` that are tolerated. */
  errorCount: number;
  /** Free-form note explaining when this baseline was last regenerated. */
  note: string;
}

/**
 * Run `tsc --noEmit --project tsconfig.test.json` and return the lines that
 * are errors located in a `test/` file. `tsconfig.test.json` also compiles
 * `src/**` (so relative `.ts` imports from tests resolve the same way the
 * src-only typecheck resolves them) — we only count errors whose path starts
 * with `test/`, so genuine test rot is the only signal.
 */
async function findTestErrors(): Promise<string[]> {
  let stdout = "";
  try {
    const result = await execFileAsync(
      "npx",
      ["tsc", "--noEmit", "--project", TSCONFIG],
      { cwd: REPO_ROOT, maxBuffer: 32 * 1024 * 1024 },
    );
    stdout = result.stdout;
  } catch (err) {
    // tsc exits non-zero when there are type errors — that's the normal path
    // here, not a crash. The diagnostics we want are on stdout.
    const e = err as { stdout?: string; stderr?: string };
    if (typeof e.stdout === "string") {
      stdout = e.stdout;
    } else {
      // No stdout means tsc itself failed to run (bad config, missing binary).
      console.error("[test-typecheck-check] tsc failed to run:", e.stderr ?? err);
      throw err;
    }
  }

  return stdout
    .split("\n")
    .map(line => line.trim())
    .filter(line => /^test\/.*error TS\d+/.test(line));
}

async function loadBaseline(): Promise<BaselineFile> {
  try {
    const raw = await readFile(BASELINE_PATH, "utf8");
    return JSON.parse(raw) as BaselineFile;
  } catch {
    return { errorCount: Number.POSITIVE_INFINITY, note: "baseline not yet seeded" };
  }
}

async function writeBaselineFile(errorCount: number): Promise<void> {
  const payload: BaselineFile = {
    errorCount,
    note: `Auto-generated by scripts/ci/test-typecheck-check.ts --write-baseline on ${new Date().toISOString()}. Issue #750 closure ratchet: shrink only. CI fails only when the count RISES.`,
  };
  await writeFile(BASELINE_PATH, JSON.stringify(payload, null, 2) + "\n", "utf8");
}

async function main(): Promise<number> {
  const errors = await findTestErrors();
  const current = errors.length;

  if (WRITE_BASELINE) {
    await writeBaselineFile(current);
    console.log(
      `[test-typecheck-check] Wrote baseline with errorCount=${current} to ${relative(REPO_ROOT, BASELINE_PATH)}`,
    );
    return 0;
  }

  const baseline = await loadBaseline();

  if (current > baseline.errorCount) {
    console.error(
      `[test-typecheck-check] Test type-errors ROSE: ${current} (baseline ${baseline.errorCount}).`,
    );
    console.error("");
    console.error("New or regressed type errors in test/** (tsx erases types, so these are invisible to npm test):");
    for (const e of errors) console.error(`  ${e}`);
    console.error("");
    console.error("Fix the new error(s). The baseline is shrink-only and must not grow.");
    return 1;
  }

  if (current < baseline.errorCount) {
    console.error(
      `[test-typecheck-check] Baseline is stale — test type-errors DROPPED to ${current} (baseline ${baseline.errorCount}).`,
    );
    console.error("");
    console.error("Re-run with --write-baseline and commit the shrunk baseline.");
    return 1;
  }

  console.log(
    `[test-typecheck-check] OK — ${current} known test type-errors, no new ones (baseline ${baseline.errorCount}).`,
  );
  return 0;
}

main().then(
  code => process.exit(code),
  err => {
    console.error("[test-typecheck-check] crash:", err);
    process.exit(2);
  },
);
