/**
 * A PATH-shim `docker` that answers the watchdog's `docker exec hydra-redis-1
 * redis-cli --raw …` round-trips over a plain TCP socket (issue #4500).
 *
 * WHY THIS EXISTS. The launch-flow suites (`test/watchdog-launch-flow.test.mts`,
 * `test/launch-flow-delivery.test.mts`) source `run_launch_flow` from
 * `scripts/hydra-watchdog.sh` and run it against the live `hydra-redis-1`
 * container. Every `rc_read` / `rc_write` in that block is a separate
 * `docker exec`, and a `docker exec` costs ~60ms of Docker-daemon exec setup
 * before redis sees a byte. One tick makes ~10 of them, so the two files spent
 * ~40s of the required `test` job — measured with a logging shim: ~430 of the
 * ~685 `docker` invocations across both files were the block's own redis
 * calls — waiting on exec setup rather than exercising any logic.
 *
 * WHAT IT CHANGES, AND WHAT IT DOES NOT.
 *   - The watchdog block under test is byte-for-byte unchanged, and so is the
 *     argv it builds: `rc_write`/`rc_read` still take their `docker` branch and
 *     still pass `exec hydra-redis-1 redis-cli --raw -n "$REDIS_DB" …`. Only the
 *     transport underneath that argv is swapped, the same way the delivery
 *     suite already swaps `curl` and `gh`.
 *   - The suites' own seed / read helpers (the ORACLE every assertion reads
 *     through) keep calling the real `docker` binary, so what the block wrote
 *     is still verified through real `redis-cli`.
 *   - Anything the shim does not recognise — a different container, a
 *     non-`--raw` call, an unknown flag, an unreachable socket — is handed to the
 *     real `docker` unchanged.
 *
 * FIDELITY IS PROVEN, NOT ASSUMED. {@link installRedisDockerShim} runs a
 * battery covering every reply shape the block consumes (nil / integer / status
 * / bulk / multi-bulk, `-n` DB selection, multi-byte values, a top-level error)
 * through BOTH the real `docker exec … redis-cli --raw` and the shim, and
 * requires identical stdout and exit status. It also requires that a write made
 * through the shim is readable through real `docker exec` — i.e. that the TCP
 * endpoint IS the container's redis. On any mismatch it returns `null`, logs
 * why, and the suites fall back to the real `docker` (slower, never wrong).
 */
import { spawnSync } from "node:child_process";
import { accessSync, constants, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { randomUUID } from "node:crypto";

import { WATCHDOG_REDIS_TIMEOUT_MS } from "./watchdog-timeouts.mts";

/** Where the container's redis is published on the host (`docker port hydra-redis-1`). */
const DEFAULT_HOST = "127.0.0.1";
const DEFAULT_PORT = 6379;

/** Absolute path of the first executable `docker` on `pathEnv`, or null. */
export function resolveRealDocker(pathEnv: string | undefined): string | null {
  for (const dir of (pathEnv ?? "").split(delimiter)) {
    if (dir === "") continue;
    const candidate = join(dir, "docker");
    try {
      accessSync(candidate, constants.X_OK);
      return candidate;
    } catch {
      /* intentional: not in this PATH entry — keep looking */
    }
  }
  return null;
}

/** Single-quote a string for safe embedding in the generated bash script. */
function shQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * The shim's bash source. Exported so the fidelity contract can be read in one
 * place; callers should use {@link installRedisDockerShim}.
 *
 * `--raw` rendering mirrors redis-cli 7's: each reply element on its own line,
 * nested arrays flattened, a nil bulk or empty array as an empty line, and a
 * top-level error reply as its message followed by an empty line (exit 0).
 */
export function redisDockerShimSource(realDocker: string, host = DEFAULT_HOST, port = DEFAULT_PORT): string {
  return `#!/usr/bin/env bash
# Generated by test/_helpers/watchdog-redis-shim.mts (issue #4500). Test-only.
REAL_DOCKER=${shQuote(realDocker)}
if [[ "\${1-}" != exec || "\${2-}" != hydra-redis-1 || "\${3-}" != redis-cli ]]; then
  exec "$REAL_DOCKER" "$@"
fi
export LC_ALL=C
args=("\${@:4}")
raw=0
db=""
while (( \${#args[@]} > 0 )); do
  case "\${args[0]}" in
    --raw) raw=1; args=("\${args[@]:1}") ;;
    -n)
      (( \${#args[@]} >= 2 )) || exec "$REAL_DOCKER" "$@"
      db="\${args[1]}"; args=("\${args[@]:2}") ;;
    -*) exec "$REAL_DOCKER" "$@" ;;
    *) break ;;
  esac
done
if (( raw != 1 || \${#args[@]} == 0 )); then
  exec "$REAL_DOCKER" "$@"
fi
if ! { exec 3<>/dev/tcp/${host}/${port}; } 2>/dev/null; then
  exec "$REAL_DOCKER" "$@"
fi
CR=$'\\r'
CRLF=$'\\r\\n'
send() {
  local out="*$#$CRLF" a
  for a in "$@"; do out+="\\$\${#a}$CRLF$a$CRLF"; done
  printf '%s' "$out" >&3
}
render() {
  local depth="$1" line t n data i
  IFS= read -r line <&3 || return 1
  line="\${line%"$CR"}"
  t="\${line:0:1}"
  n="\${line:1}"
  case "$t" in
    '+'|':') printf '%s\\n' "$n" ;;
    '-')
      if (( depth == 0 )); then printf '%s\\n\\n' "$n"; else printf '%s\\n' "$n"; fi ;;
    '$')
      if [[ "$n" == "-1" ]]; then
        printf '\\n'
      else
        data=""
        if (( n > 0 )); then IFS= read -r -d '' -N "$n" data <&3 || return 1; fi
        IFS= read -r line <&3 || return 1
        printf '%s\\n' "$data"
      fi ;;
    '*')
      if (( n <= 0 )); then
        printf '\\n'
      else
        for (( i = 0; i < n; i++ )); do render $(( depth + 1 )) || return 1; done
      fi ;;
    *) return 1 ;;
  esac
}
if [[ -n "$db" ]]; then
  send SELECT "$db"
  IFS= read -r sel <&3 || exec "$REAL_DOCKER" "$@"
  [[ "\${sel%"$CR"}" == "+OK" ]] || exec "$REAL_DOCKER" "$@"
fi
send "\${args[@]}"
render 0 || exit 1
exit 0
`;
}

/** One `redis-cli --raw` invocation result, as the fidelity battery compares it. */
interface CliResult {
  status: number | null;
  stdout: string;
}

function runCli(bin: string, cliArgs: string[]): CliResult {
  const r = spawnSync(bin, ["exec", "hydra-redis-1", "redis-cli", "--raw", ...cliArgs], {
    encoding: "utf-8",
    timeout: WATCHDOG_REDIS_TIMEOUT_MS,
  });
  if (r.error || r.signal) return { status: null, stdout: `spawn failed: ${String(r.error ?? r.signal)}` };
  return { status: r.status, stdout: r.stdout ?? "" };
}

/**
 * The fidelity battery: every reply shape `run_launch_flow` consumes. Each
 * entry is run twice on DISJOINT keys — once through real docker, once through
 * the shim — so stateful commands (SET NX) see identical starting state.
 */
function battery(key: (name: string) => string): string[][] {
  return [
    ["-n", "0", "GET", key("str")], // nil bulk
    ["-n", "0", "EXISTS", key("str")], // integer 0
    ["-n", "0", "HGETALL", key("hash")], // empty multi-bulk
    ["-n", "0", "SET", key("str"), "1700000000000", "NX"], // status OK
    ["-n", "0", "SET", key("str"), "1", "NX"], // nil (NX refused)
    ["-n", "0", "GET", key("str")], // bulk
    ["-n", "0", "EXISTS", key("str")], // integer 1
    ["-n", "0", "HSET", key("hash"), "reason", "eligible launch", "latency_ms", "", "class", "héllo wörld"],
    ["-n", "0", "HGETALL", key("hash")], // multi-bulk incl. an empty + a multi-byte value
    ["-n", "0", "XADD", key("stream"), "1-1", "type", "launch:quota_stretch", "payload", '{"signal":"quota","durationMs":5000}'],
    ["-n", "0", "DEL", key("str"), key("hash"), key("stream")], // integer 3
    ["-n", "9", "SET", key("db9"), "x"], // SELECT path
    ["-n", "9", "GET", key("db9")],
    ["-n", "0", "GET", key("db9")], // must be nil: the SET above went to db 9
    ["-n", "9", "DEL", key("db9")],
    ["-n", "0", "INCR"], // top-level error reply
  ];
}

/**
 * Install the shim into a fresh temp dir and prove it equivalent to the real
 * transport. Returns the directory to PREPEND to a child's PATH, or `null` when
 * the shim cannot be proven equivalent here (callers then keep the real
 * `docker`). Callers remove the directory with {@link removeRedisDockerShim}.
 */
export function installRedisDockerShim(label: string): string | null {
  const realDocker = resolveRealDocker(process.env.PATH);
  if (realDocker === null) return null;

  const dir = join(tmpdir(), `hydra-watchdog-redis-shim-${label}-${process.pid}-${randomUUID().slice(0, 8)}`);
  mkdirSync(dir, { recursive: true });
  const shim = join(dir, "docker");
  writeFileSync(shim, redisDockerShimSource(realDocker), { mode: 0o755 });

  const ns = `hydra:test:redis-shim-fidelity-${process.pid}-${randomUUID().slice(0, 8)}`;
  const reject = (why: string): null => {
    console.error(`[watchdog-redis-shim] falling back to real docker exec (slower, still correct): ${why}`);
    removeRedisDockerShim(dir);
    return null;
  };

  const realCases = battery((n) => `${ns}:real:${n}`);
  const shimCases = battery((n) => `${ns}:shim:${n}`);
  for (let i = 0; i < realCases.length; i++) {
    const real = runCli(realDocker, realCases[i]);
    const viaShim = runCli(shim, shimCases[i]);
    if (real.status !== viaShim.status || real.stdout !== viaShim.stdout) {
      return reject(
        `fidelity mismatch on \`redis-cli --raw ${realCases[i].slice(2, 3).join(" ")}\`: ` +
          `real=${JSON.stringify(real)} shim=${JSON.stringify(viaShim)}`,
      );
    }
  }

  // Same server: a shim write must be visible through the real transport.
  const probe = `${ns}:same-server`;
  const token = randomUUID();
  const wrote = runCli(shim, ["-n", "0", "SET", probe, token]);
  const readBack = runCli(realDocker, ["-n", "0", "GET", probe]);
  runCli(realDocker, ["-n", "0", "DEL", probe]);
  if (wrote.stdout !== "OK\n" || readBack.stdout !== `${token}\n`) {
    return reject(
      `the TCP endpoint ${DEFAULT_HOST}:${DEFAULT_PORT} is not hydra-redis-1's redis ` +
        `(shim SET -> ${JSON.stringify(wrote)}, real GET -> ${JSON.stringify(readBack)})`,
    );
  }
  return dir;
}

/** Remove a shim directory created by {@link installRedisDockerShim}. */
export function removeRedisDockerShim(dir: string | null): void {
  if (dir === null) return;
  try {
    rmSync(dir, { recursive: true, force: true });
  } catch (err) {
    console.error(`[watchdog-redis-shim] could not remove ${dir}: ${String(err)}`);
  }
}

/** `pathEnv` with the shim dir prepended, or unchanged when no shim is installed. */
export function withRedisDockerShim(dir: string | null, pathEnv: string | undefined): string {
  const base = pathEnv ?? "";
  return dir === null ? base : `${dir}${delimiter}${base}`;
}
